In [1]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
data = pd.read_csv("../data/CAB_23_MP.csv", low_memory=False)

In [3]:
data.shape

(261137, 54)

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 261137 entries, 0 to 261136
Data columns (total 54 columns):
state_code                          261137 non-null int64
district_code                       261137 non-null int64
rural_urban                         261137 non-null int64
stratum                             261137 non-null int64
psu_id                              261137 non-null int64
ahs_house_unit                      261137 non-null int64
house_hold_no                       261137 non-null int64
date_survey                         261137 non-null object
test_salt_iodine                    261137 non-null int64
record_code_iodine                  261137 non-null int64
record_code_iodine_reason           3151 non-null object
sl_no                               261137 non-null int64
sex                                 261137 non-null int64
usual_residance                     261137 non-null int64
usual_residance_reason              6413 non-null object
identification_code                 261136 non-null float64
age_code                            261137 non-null object
age                                 261137 non-null int64
date_of_birth                       261137 non-null int64
month_of_birth                      261137 non-null int64
year_of_birth                       261137 non-null int64
weight_measured                     261137 non-null int64
weight_in_kg                        261137 non-null float64
length_height_measured              261137 non-null int64
length_height_code                  261137 non-null object
length_height_cm                    261137 non-null float64
haemoglobin_test                    261137 non-null int64
haemoglobin                         261137 non-null int64
haemoglobin_level                   261137 non-null float64
bp_systolic                         261137 non-null int64
bp_systolic_2_reading               261137 non-null int64
bp_diastolic                        261137 non-null int64
bp_diastolic_2reading               261137 non-null int64
pulse_rate                          261137 non-null int64
pulse_rate_2_reading                261137 non-null int64
diabetes_test                       261137 non-null int64
fasting_blood_glucose               261137 non-null int64
fasting_blood_glucose_mg_dl         261137 non-null float64
marital_status                      261137 non-null int64
gauna_perfor_not_perfor             261137 non-null int64
duration_pregnanacy                 261137 non-null int64
first_breast_feeding                261137 non-null int64
is_cur_breast_feeding               261137 non-null int64
day_or_month_for_breast_feeding_    261137 non-null object
day_or_month_for_breast_feeding     261137 non-null int64
water_month                         261137 non-null int64
ani_milk_month                      261137 non-null int64
semisolid_month_or_day              261137 non-null int64
solid_month                         261137 non-null int64
vegetables_month_or_day             261137 non-null int64
illness_type                        261137 non-null int64
illness_duration                    261137 non-null int64
treatment_type                      261137 non-null int64
v54                                 0 non-null float64
dtypes: float64(6), int64(42), object(6)
memory usage: 107.6+ MB

In [5]:
data.columns.values

array(['state_code', 'district_code', 'rural_urban', 'stratum', 'psu_id',
       'ahs_house_unit', 'house_hold_no', 'date_survey',
       'test_salt_iodine', 'record_code_iodine',
       'record_code_iodine_reason', 'sl_no', 'sex', 'usual_residance',
       'usual_residance_reason', 'identification_code', 'age_code', 'age',
       'date_of_birth', 'month_of_birth', 'year_of_birth',
       'weight_measured', 'weight_in_kg', 'length_height_measured',
       'length_height_code', 'length_height_cm', 'haemoglobin_test',
       'haemoglobin', 'haemoglobin_level', 'bp_systolic',
       'bp_systolic_2_reading', 'bp_diastolic', 'bp_diastolic_2reading',
       'pulse_rate', 'pulse_rate_2_reading', 'diabetes_test',
       'fasting_blood_glucose', 'fasting_blood_glucose_mg_dl',
       'marital_status', 'gauna_perfor_not_perfor', 'duration_pregnanacy',
       'first_breast_feeding', 'is_cur_breast_feeding',
       'day_or_month_for_breast_feeding_',
       'day_or_month_for_breast_feeding', 'water_month', 'ani_milk_month',
       'semisolid_month_or_day', 'solid_month', 'vegetables_month_or_day',
       'illness_type', 'illness_duration', 'treatment_type', 'v54'], dtype=object)

In [6]:
data = data.drop([ 'psu_id','ahs_house_unit','house_hold_no', 'date_survey',
                  'test_salt_iodine', 'record_code_iodine_reason', 'sl_no', 'usual_residance_reason',
                  'identification_code', 'date_of_birth', 'year_of_birth', 'weight_measured',
                  'length_height_measured', 'length_height_code', 'haemoglobin_test', 'haemoglobin', 'bp_systolic',
                  'bp_systolic_2_reading', 'bp_diastolic', 'bp_diastolic_2reading', 'pulse_rate',
                  'pulse_rate_2_reading', 'diabetes_test', 'fasting_blood_glucose', 'fasting_blood_glucose_mg_dl',
                  'marital_status', 'gauna_perfor_not_perfor', 'duration_pregnanacy', 'illness_duration', 'v54'],
                axis = 1)

In [7]:
data.shape

(261137, 24)

In [8]:
data.columns.values

array(['state_code', 'district_code', 'rural_urban', 'stratum',
       'record_code_iodine', 'sex', 'usual_residance', 'age_code', 'age',
       'month_of_birth', 'weight_in_kg', 'length_height_cm',
       'haemoglobin_level', 'first_breast_feeding',
       'is_cur_breast_feeding', 'day_or_month_for_breast_feeding_',
       'day_or_month_for_breast_feeding', 'water_month', 'ani_milk_month',
       'semisolid_month_or_day', 'solid_month', 'vegetables_month_or_day',
       'illness_type', 'treatment_type'], dtype=object)

In [9]:
data = data.drop(data[(data['age_code'] == 'Y') & (data['age'] > 5) | (data['illness_type'] == -1)].index)

In [10]:
data.shape

(14661, 24)

In [11]:
data['illness_type'].value_counts()

0    11159
2     1841
1     1197
3      403
4       61
Name: illness_type, dtype: int64

In [12]:
data['illness_type'].value_counts() / 146.61

0    76.113498
2    12.557124
1     8.164518
3     2.748789
4     0.416070
Name: illness_type, dtype: float64

In [13]:
data['age_code'].value_counts()

Y    12337
M     2235
D       79
y        9
m        1
Name: age_code, dtype: int64

In [14]:
data['age_code'][data['age_code'] == 'm'] = 'M'
data['age_code'][data['age_code'] == 'y'] = 'Y'

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [15]:
data['age_code'].value_counts()

Y    12346
M     2236
D       79
Name: age_code, dtype: int64

In [16]:
print(data['rural_urban'].value_counts())
print(data['stratum'].value_counts())
print(data['record_code_iodine'].value_counts())
print(data['sex'].value_counts())
print(data['usual_residance'].value_counts())
print(data['age_code'].value_counts())
print(data['month_of_birth'].value_counts())

1    11018
2     3643
Name: rural_urban, dtype: int64
1    6082
2    4936
0    3643
Name: stratum, dtype: int64
3    13720
2      696
1      245
Name: record_code_iodine, dtype: int64
1    7747
2    6914
Name: sex, dtype: int64
1    14658
2        3
Name: usual_residance, dtype: int64
Y    12346
M     2236
D       79
Name: age_code, dtype: int64
6     3510
1     2829
8     1042
9      883
2      867
7      845
12     827
5      818
4      781
3      776
11     750
10     733
Name: month_of_birth, dtype: int64

In [17]:
data['illness_type'].groupby(data['month_of_birth']).mean()

month_of_birth
1     0.273595
2     0.464821
3     0.490979
4     0.532650
5     0.490220
6     0.428490
7     0.514793
8     0.438580
9     0.502831
10    0.506139
11    0.504000
12    0.444982
Name: illness_type, dtype: float64

In [18]:
data.shape

(14661, 24)

In [19]:
data['age_code'].value_counts()

Y    12346
M     2236
D       79
Name: age_code, dtype: int64

In [20]:
data['record_code_iodine'].value_counts()

3    13720
2      696
1      245
Name: record_code_iodine, dtype: int64

In [21]:
data['sex'].value_counts()

1    7747
2    6914
Name: sex, dtype: int64

In [22]:
data['day_or_month_for_breast_feeding_'].value_counts()

M     7612
-1    6945
D      103
m        1
Name: day_or_month_for_breast_feeding_, dtype: int64

In [23]:
data['day_or_month_for_breast_feeding_'][data['day_or_month_for_breast_feeding_'] == 'm'] = 'M'

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [24]:
data['day_or_month_for_breast_feeding_'].value_counts()

M     7613
-1    6945
D      103
Name: day_or_month_for_breast_feeding_, dtype: int64

In [25]:
#droping birth month
data = data.drop('month_of_birth', axis=1)
data.shape

(14661, 23)

In [26]:
data.columns.unique()

Index(['state_code', 'district_code', 'rural_urban', 'stratum',
       'record_code_iodine', 'sex', 'usual_residance', 'age_code', 'age',
       'weight_in_kg', 'length_height_cm', 'haemoglobin_level',
       'first_breast_feeding', 'is_cur_breast_feeding',
       'day_or_month_for_breast_feeding_', 'day_or_month_for_breast_feeding',
       'water_month', 'ani_milk_month', 'semisolid_month_or_day',
       'solid_month', 'vegetables_month_or_day', 'illness_type',
       'treatment_type'],
      dtype='object')

In [27]:
data = data.drop('rural_urban',axis=1)

In [28]:
data.columns.values

array(['state_code', 'district_code', 'stratum', 'record_code_iodine',
       'sex', 'usual_residance', 'age_code', 'age', 'weight_in_kg',
       'length_height_cm', 'haemoglobin_level', 'first_breast_feeding',
       'is_cur_breast_feeding', 'day_or_month_for_breast_feeding_',
       'day_or_month_for_breast_feeding', 'water_month', 'ani_milk_month',
       'semisolid_month_or_day', 'solid_month', 'vegetables_month_or_day',
       'illness_type', 'treatment_type'], dtype=object)

In [29]:
data = data.drop(['stratum', 'usual_residance'],axis=1)

In [30]:
data.columns.values

array(['state_code', 'district_code', 'record_code_iodine', 'sex',
       'age_code', 'age', 'weight_in_kg', 'length_height_cm',
       'haemoglobin_level', 'first_breast_feeding',
       'is_cur_breast_feeding', 'day_or_month_for_breast_feeding_',
       'day_or_month_for_breast_feeding', 'water_month', 'ani_milk_month',
       'semisolid_month_or_day', 'solid_month', 'vegetables_month_or_day',
       'illness_type', 'treatment_type'], dtype=object)

In [31]:
data['weight_in_kg'][data[data['weight_in_kg'] == -1].index].value_counts()

-1.0    1516
Name: weight_in_kg, dtype: int64

In [32]:
print(data['record_code_iodine'][data[data['record_code_iodine'] == -1].index].value_counts())
print(data['sex'][data[data['sex'] == -1].index].value_counts())
print(data['age_code'][data[data['age_code'] == -1].index].value_counts())
print(data['age'][data[data['age'] == -1].index].value_counts())
print(data['weight_in_kg'][data[data['weight_in_kg'] == -1].index].value_counts())
print(data['length_height_cm'][data[data['length_height_cm'] == -1].index].value_counts())
print(data['haemoglobin_level'][data[data['haemoglobin_level'] == -1].index].value_counts())
print(data['first_breast_feeding'][data[data['first_breast_feeding'] == -1].index].value_counts())
print(data['is_cur_breast_feeding'][data[data['is_cur_breast_feeding'] == -1].index].value_counts())
print(data['day_or_month_for_breast_feeding_'][data[data['day_or_month_for_breast_feeding_'] == -1].index].value_counts())
print(data['day_or_month_for_breast_feeding'][data[data['day_or_month_for_breast_feeding'] == -1].index].value_counts())
print(data['water_month'][data[data['water_month'] == -1].index].value_counts())
print(data['ani_milk_month'][data[data['ani_milk_month'] == -1].index].value_counts())
print(data['semisolid_month_or_day'][data[data['semisolid_month_or_day'] == -1].index].value_counts())
print(data['solid_month'][data[data['solid_month'] == -1].index].value_counts())
print(data['vegetables_month_or_day'][data[data['vegetables_month_or_day'] == -1].index].value_counts())

Series([], Name: record_code_iodine, dtype: int64)
Series([], Name: sex, dtype: int64)
Series([], Name: age_code, dtype: int64)
Series([], Name: age, dtype: int64)
-1.0    1516
Name: weight_in_kg, dtype: int64
-1.0    1527
Name: length_height_cm, dtype: int64
-1.0    7354
Name: haemoglobin_level, dtype: int64
-1    6934
Name: first_breast_feeding, dtype: int64
-1    6941
Name: is_cur_breast_feeding, dtype: int64
Series([], Name: day_or_month_for_breast_feeding_, dtype: int64)
-1    6951
Name: day_or_month_for_breast_feeding, dtype: int64
-1    6944
Name: water_month, dtype: int64
-1    6949
Name: ani_milk_month, dtype: int64
-1    6948
Name: semisolid_month_or_day, dtype: int64
-1    6961
Name: solid_month, dtype: int64
-1    6962
Name: vegetables_month_or_day, dtype: int64

In [33]:
data.shape

(14661, 20)

In [34]:
data['water_month'][data[data['water_month'] == -1].index].value_counts()

-1    6944
Name: water_month, dtype: int64

In [35]:
data['semisolid_month_or_day'][data[data['semisolid_month_or_day'] == -1].index].value_counts()

-1    6948
Name: semisolid_month_or_day, dtype: int64

In [36]:
data['is_cur_breast_feeding'][data[(data['is_cur_breast_feeding'] == -1)].index].value_counts()

-1    6941
Name: is_cur_breast_feeding, dtype: int64

In [37]:
data['is_cur_breast_feeding'][data[(data['is_cur_breast_feeding'] == -1) & (data['age']>2) & (data['age_code'] == 'Y')].index].value_counts()

-1    6757
Name: is_cur_breast_feeding, dtype: int64

In [38]:
# data['is_cur_breast_feeding'][data[(data['age_code'] == 'Y') & (data['age'] > 2) & (data['is_cur_breast_feeding'] == -1)].index] = 2
data.loc[((data['age']>2) & (data['age_code'] == 'Y') & (data['is_cur_breast_feeding'] == -1)),'is_cur_breast_feeding'] = 2

In [39]:
data['is_cur_breast_feeding'][data[data['is_cur_breast_feeding'] == -1].index].value_counts()

-1    184
Name: is_cur_breast_feeding, dtype: int64

In [40]:
data['is_cur_breast_feeding'] = data['is_cur_breast_feeding'].replace(-1, 1)

In [41]:
data['age'][data[data['is_cur_breast_feeding'] == -1].index]

Series([], Name: age, dtype: int64)

In [42]:
data['weight_in_kg'][data[(data['weight_in_kg'] == -1)].index].value_counts()

-1.0    1516
Name: weight_in_kg, dtype: int64

In [43]:
data['age_code'][data[(data['weight_in_kg'] == -1)].index].value_counts()

Y    1385
D      79
M      52
Name: age_code, dtype: int64

In [44]:
for y in data['age_code'].unique():
    for i in data['age'][data[data['age_code'] == y].index].unique():
        x = data['weight_in_kg'][data[(data['age_code'] == y) & (data['age'] == i) & (data['weight_in_kg'] != -1)].index].mean()
        data.loc[((data['age_code'] == y) & (data['age'] == i) & (data['weight_in_kg'] == -1)), 'weight_in_kg'] = x

In [45]:
for y in data['age_code'].unique():
    for i in data['age'][data[data['age_code'] == y].index].unique():
        x = data['weight_in_kg'][data[(data['age_code'] == y) & (data['age'] == i) & (data['weight_in_kg'] != -1)].index].mean()
        data['weight_in_kg'] = data['weight_in_kg'].fillna(x)

In [46]:
data['weight_in_kg'][data[(data['weight_in_kg'] == -1)].index].value_counts()

Series([], Name: weight_in_kg, dtype: int64)

In [47]:
data['length_height_cm'][data[(data['length_height_cm'] == -1)].index].value_counts()

-1.0    1527
Name: length_height_cm, dtype: int64

In [48]:
for y in data['age_code'].unique():
    for i in data['age'][data[data['age_code'] == y].index].unique():
        x = data['length_height_cm'][data[(data['age_code'] == y) & (data['age'] == i) & (data['length_height_cm'] != -1)].index].mean()
        data.loc[((data['age_code'] == y) & (data['age'] == i) & (data['length_height_cm'] == -1)), 'length_height_cm'] = x

In [49]:
for y in data['age_code'].unique():
    for i in data['age'][data[data['age_code'] == y].index].unique():
        x = data['length_height_cm'][data[(data['age_code'] == y) & (data['age'] == i) & (data['length_height_cm'] != -1)].index].mean()
        data['length_height_cm'] = data['length_height_cm'].fillna(x)

In [50]:
data['length_height_cm'][data[(data['length_height_cm'] == -1)].index].value_counts()

Series([], Name: length_height_cm, dtype: int64)

In [51]:
data['haemoglobin_level'][data[(data['haemoglobin_level'] == -1)].index].value_counts()

-1.0    7354
Name: haemoglobin_level, dtype: int64

In [52]:
for y in data['age_code'].unique():
    for i in data['age'][data[data['age_code'] == y].index].unique():
        x = data['haemoglobin_level'][data[(data['age_code'] == y) & (data['age'] == i) & (data['haemoglobin_level'] != -1)].index].mean()
        data.loc[((data['age_code'] == y) & (data['age'] == i) & (data['haemoglobin_level'] == -1)), 'haemoglobin_level'] = x

In [53]:
for y in data['age_code'].unique():
    for i in data['age'][data[data['age_code'] == y].index].unique():
        x = data['haemoglobin_level'][data[(data['age_code'] == y) & (data['age'] == i) & (data['haemoglobin_level'] != -1)].index].mean()
        data['haemoglobin_level'] = data['haemoglobin_level'].fillna(x)

In [54]:
data['haemoglobin_level'][data[(data['haemoglobin_level'] == -1)].index].value_counts()

Series([], Name: haemoglobin_level, dtype: int64)

In [55]:
data['first_breast_feeding'][data[(data['first_breast_feeding'] == -1)].index].value_counts()

-1    6934
Name: first_breast_feeding, dtype: int64

In [56]:
for i in data['district_code'].unique():
    print(i)
    x = data['district_code'][data[data['district_code']==i].index].value_counts()
    print(x[i])
    print((data['first_breast_feeding'][data[data['district_code']==i].index].value_counts().sort_index())*100/x[i])
    print("----------------------------------------------------")

1
546
-1    44.688645
 1    47.435897
 2     7.692308
 4     0.183150
Name: first_breast_feeding, dtype: float64
----------------------------------------------------
2
221
-1    55.656109
 1    34.389140
 2     9.954751
Name: first_breast_feeding, dtype: float64
----------------------------------------------------
3
318
-1    58.176101
 1    37.106918
 2     4.716981
Name: first_breast_feeding, dtype: float64
----------------------------------------------------
4
356
-1    52.808989
 1    34.831461
 2    12.078652
 3     0.280899
Name: first_breast_feeding, dtype: float64
----------------------------------------------------
5
239
-1    60.251046
 1    33.054393
 2     6.694561
Name: first_breast_feeding, dtype: float64
----------------------------------------------------
6
474
-1    55.696203
 1    37.552743
 2     6.751055
Name: first_breast_feeding, dtype: float64
----------------------------------------------------
7
337
-1    49.258160
 1    36.795252
 2    13.056380
 3     0.890208
Name: first_breast_feeding, dtype: float64
----------------------------------------------------
8
426
-1    46.948357
 1    42.253521
 2     8.685446
 3     2.112676
Name: first_breast_feeding, dtype: float64
----------------------------------------------------
9
432
-1    44.444444
 1    30.787037
 2    23.379630
 3     1.388889
Name: first_breast_feeding, dtype: float64
----------------------------------------------------
10
405
-1    56.543210
 1    31.851852
 2    11.358025
 3     0.246914
Name: first_breast_feeding, dtype: float64
----------------------------------------------------
11
460
-1    41.521739
 1    47.173913
 2    11.304348
Name: first_breast_feeding, dtype: float64
----------------------------------------------------
12
513
-1    47.563353
 1    43.469786
 2     5.068226
 3     3.898635
Name: first_breast_feeding, dtype: float64
----------------------------------------------------
13
255
-1    36.078431
 1    54.117647
 2     9.803922
Name: first_breast_feeding, dtype: float64
----------------------------------------------------
14
163
-1    12.883436
 1    42.944785
 2    41.717791
 3     2.453988
Name: first_breast_feeding, dtype: float64
----------------------------------------------------
15
330
-1    39.090909
 1    50.303030
 2    10.606061
Name: first_breast_feeding, dtype: float64
----------------------------------------------------
16
361
-1    36.011080
 1    44.875346
 2    18.559557
 3     0.554017
Name: first_breast_feeding, dtype: float64
----------------------------------------------------
17
322
-1    38.819876
 1    53.726708
 2     7.453416
Name: first_breast_feeding, dtype: float64
----------------------------------------------------
18
135
-1    65.925926
 1    22.222222
 2    11.111111
 3     0.740741
Name: first_breast_feeding, dtype: float64
----------------------------------------------------
19
247
-1    69.230769
 1    17.408907
 2    11.336032
 3     1.619433
 4     0.404858
Name: first_breast_feeding, dtype: float64
----------------------------------------------------
20
219
-1    64.383562
 1    31.506849
 2     4.109589
Name: first_breast_feeding, dtype: float64
----------------------------------------------------
21
352
-1    51.136364
 1    39.204545
 2     8.238636
 3     1.420455
Name: first_breast_feeding, dtype: float64
----------------------------------------------------
22
270
-1    58.518519
 1    27.037037
 2    13.703704
 3     0.370370
 4     0.370370
Name: first_breast_feeding, dtype: float64
----------------------------------------------------
23
477
-1    52.830189
 1    44.654088
 2     2.306080
 4     0.209644
Name: first_breast_feeding, dtype: float64
----------------------------------------------------
24
312
-1    64.102564
 1    32.051282
 2     3.846154
Name: first_breast_feeding, dtype: float64
----------------------------------------------------
25
235
-1    68.936170
 1    28.510638
 2     2.553191
Name: first_breast_feeding, dtype: float64
----------------------------------------------------
26
471
-1    44.585987
 1    30.360934
 2    17.622081
 3     6.369427
 4     0.849257
 5     0.212314
Name: first_breast_feeding, dtype: float64
----------------------------------------------------
27
290
-1    64.482759
 1    27.931034
 2     7.586207
Name: first_breast_feeding, dtype: float64
----------------------------------------------------
28
289
-1    57.439446
 1    38.062284
 2     4.498270
Name: first_breast_feeding, dtype: float64
----------------------------------------------------
29
457
-1    53.391685
 1    33.698031
 2    12.472648
 3     0.437637
Name: first_breast_feeding, dtype: float64
----------------------------------------------------
30
199
-1    62.311558
 1    36.180905
 2     1.507538
Name: first_breast_feeding, dtype: float64
----------------------------------------------------
31
285
-1    37.192982
 1    27.368421
 2    33.684211
 3     1.754386
Name: first_breast_feeding, dtype: float64
----------------------------------------------------
32
311
-1    47.909968
 1    33.762058
 2    16.398714
 3     0.964630
 4     0.321543
 5     0.643087
Name: first_breast_feeding, dtype: float64
----------------------------------------------------
33
267
-1    68.164794
 1    27.715356
 2     3.745318
 3     0.374532
Name: first_breast_feeding, dtype: float64
----------------------------------------------------
34
201
-1    18.905473
 1    77.114428
 2     3.980100
Name: first_breast_feeding, dtype: float64
----------------------------------------------------
35
349
-1    43.553009
 1    40.687679
 2    11.461318
 3     3.724928
 4     0.286533
 5     0.286533
Name: first_breast_feeding, dtype: float64
----------------------------------------------------
36
207
-1    25.120773
 1    53.140097
 2    12.560386
 3     6.763285
 4     1.932367
 5     0.483092
Name: first_breast_feeding, dtype: float64
----------------------------------------------------
37
420
-1    43.095238
 1    48.095238
 2     6.190476
 3     1.904762
 4     0.714286
Name: first_breast_feeding, dtype: float64
----------------------------------------------------
38
234
-1    14.529915
 1    76.923077
 2     8.547009
Name: first_breast_feeding, dtype: float64
----------------------------------------------------
39
251
-1    32.270916
 1    52.988048
 2     9.960159
 3     3.984064
 4     0.796813
Name: first_breast_feeding, dtype: float64
----------------------------------------------------
40
210
-1    28.571429
 1    43.809524
 2    26.190476
 3     1.428571
Name: first_breast_feeding, dtype: float64
----------------------------------------------------
41
414
-1    38.164251
 1    18.357488
 2    39.130435
 3     3.140097
 4     1.207729
Name: first_breast_feeding, dtype: float64
----------------------------------------------------
42
361
-1    42.382271
 1    33.518006
 2    24.099723
Name: first_breast_feeding, dtype: float64
----------------------------------------------------
43
285
-1    30.526316
 1    39.649123
 2    27.368421
 3     2.456140
Name: first_breast_feeding, dtype: float64
----------------------------------------------------
44
273
-1    36.630037
 1    25.274725
 2    34.432234
 3     1.831502
 4     1.831502
Name: first_breast_feeding, dtype: float64
----------------------------------------------------
45
482
-1    51.867220
 1    11.825726
 2    34.854772
 3     1.452282
Name: first_breast_feeding, dtype: float64
----------------------------------------------------

In [57]:
for i in data['district_code'].unique():
    x = data['first_breast_feeding'][data[(data['district_code'] == i) & (data['first_breast_feeding'] != -1)].index].value_counts()
    y = x[x == x.max()].index.item()
    data.loc[((data['district_code'] == i) & (data['first_breast_feeding'] == -1)), 'first_breast_feeding'] = y

In [58]:
for i in data['district_code'].unique():
    x = data['first_breast_feeding'][data[(data['district_code'] == i) & (data['first_breast_feeding'] != -1)].index].value_counts()
    y = x[x == x.max()].index.item()
    data['first_breast_feeding'] = data['first_breast_feeding'].fillna(y)

In [59]:
data['first_breast_feeding'][data[(data['first_breast_feeding'] == -1)].index].value_counts()

Series([], Name: first_breast_feeding, dtype: int64)

In [60]:
data['day_or_month_for_breast_feeding'][data[(data['day_or_month_for_breast_feeding'] == -1)].index].value_counts()

-1    6951
Name: day_or_month_for_breast_feeding, dtype: int64

In [61]:
for i in data['district_code'].unique():
    print(i)
    x = data['district_code'][data[data['district_code']==i].index].value_counts()
    print(x[i])
    print((data['day_or_month_for_breast_feeding'][data[data['district_code']==i].index].value_counts().sort_index())*100/x[i])
    print("----------------------------------------------------")

1
546
-1     44.688645
 0      2.014652
 1      1.098901
 2      1.098901
 3      2.564103
 4      4.761905
 5     15.750916
 6     25.824176
 7      1.465201
 9      0.183150
 10     0.183150
 15     0.366300
Name: day_or_month_for_breast_feeding, dtype: float64
----------------------------------------------------
2
221
-1     55.656109
 0      3.167421
 1      0.452489
 2      0.904977
 3      1.809955
 4      3.167421
 5      4.072398
 6     12.217195
 7      4.524887
 8      0.452489
 9      1.357466
 10     0.452489
 11     0.452489
 12     1.357466
 13     2.714932
 14     0.452489
 16     0.904977
 18     0.904977
 20     0.904977
 21     1.357466
 23     0.452489
 24     0.452489
 32     0.452489
 33     0.452489
 34     0.452489
 36     0.452489
Name: day_or_month_for_breast_feeding, dtype: float64
----------------------------------------------------
3
318
-1     58.176101
 0      0.943396
 1      1.886792
 2      1.886792
 3      2.201258
 4      1.886792
 5      1.257862
 6     21.069182
 7      0.943396
 8      1.572327
 9      0.628931
 10     2.515723
 11     0.628931
 12     1.572327
 13     0.314465
 14     0.314465
 16     0.314465
 20     0.628931
 22     0.628931
 23     0.314465
 28     0.314465
Name: day_or_month_for_breast_feeding, dtype: float64
----------------------------------------------------
4
356
-1     53.089888
 0      1.123596
 1      0.280899
 2      1.123596
 3      0.842697
 4      1.404494
 5      3.370787
 6     24.157303
 7      2.247191
 8      1.966292
 9      1.404494
 10     0.842697
 11     0.842697
 12     1.685393
 13     1.966292
 14     1.123596
 15     1.404494
 16     0.280899
 19     0.280899
 20     0.280899
 24     0.280899
Name: day_or_month_for_breast_feeding, dtype: float64
----------------------------------------------------
5
239
-1     60.251046
 0      3.347280
 1      0.836820
 2      2.928870
 3      2.928870
 4      4.184100
 5      3.347280
 6     19.246862
 7      1.673640
 9      0.418410
 13     0.418410
 14     0.418410
Name: day_or_month_for_breast_feeding, dtype: float64
----------------------------------------------------
6
474
-1     56.751055
 0      0.421941
 1      0.210970
 2      0.843882
 3      1.265823
 4      1.265823
 5      2.953586
 6     20.042194
 7      1.687764
 8      1.054852
 9      1.265823
 10     1.476793
 11     0.843882
 12     2.742616
 13     0.421941
 14     1.898734
 16     1.054852
 18     1.265823
 20     0.210970
 21     0.421941
 23     0.421941
 29     0.210970
 30     0.210970
 33     0.421941
 35     0.210970
 36     0.421941
Name: day_or_month_for_breast_feeding, dtype: float64
----------------------------------------------------
7
337
-1     49.554896
 0      2.670623
 1      1.483680
 2      1.186944
 3      2.967359
 4      1.186944
 5      5.341246
 6     25.816024
 7      8.011869
 8      0.296736
 9      0.593472
 22     0.296736
 27     0.296736
 30     0.296736
Name: day_or_month_for_breast_feeding, dtype: float64
----------------------------------------------------
8
426
-1     46.948357
 0      0.234742
 1      1.173709
 2      2.347418
 3      1.643192
 4      2.816901
 5     29.342723
 6     15.258216
 20     0.234742
Name: day_or_month_for_breast_feeding, dtype: float64
----------------------------------------------------
9
432
-1    44.444444
 0     2.083333
 2     1.388889
 3     1.620370
 4     4.166667
 5    23.148148
 6    23.148148
Name: day_or_month_for_breast_feeding, dtype: float64
----------------------------------------------------
10
405
-1    56.543210
 0     2.469136
 1     1.234568
 2     2.222222
 3     1.234568
 4     4.938272
 5    20.740741
 6    10.617284
Name: day_or_month_for_breast_feeding, dtype: float64
----------------------------------------------------
11
460
-1    41.521739
 0     0.217391
 1     1.086957
 2     3.043478
 3     2.826087
 4     6.304348
 5    26.956522
 6    18.043478
Name: day_or_month_for_breast_feeding, dtype: float64
----------------------------------------------------
12
513
-1    47.563353
 0     2.144250
 1     0.584795
 2     1.949318
 3     1.949318
 4     4.873294
 5    30.994152
 6     9.941520
Name: day_or_month_for_breast_feeding, dtype: float64
----------------------------------------------------
13
255
-1     36.078431
 0      1.176471
 1      1.568627
 2      5.490196
 3      3.137255
 4      6.274510
 5     16.862745
 6     29.019608
 17     0.392157
Name: day_or_month_for_breast_feeding, dtype: float64
----------------------------------------------------
14
163
-1     12.883436
 0      1.226994
 1      3.067485
 2      2.453988
 3     11.656442
 4     30.674847
 5     22.085890
 6     12.883436
 8      0.613497
 15     0.613497
 27     0.613497
 28     0.613497
 29     0.613497
Name: day_or_month_for_breast_feeding, dtype: float64
----------------------------------------------------
15
330
-1     38.787879
 2      4.242424
 3      2.121212
 4      3.030303
 5     45.757576
 6      5.454545
 15     0.303030
 16     0.303030
Name: day_or_month_for_breast_feeding, dtype: float64
----------------------------------------------------
16
361
-1    36.011080
 0     1.662050
 1     0.277008
 3     0.554017
 4     4.709141
 5    36.011080
 6    20.775623
Name: day_or_month_for_breast_feeding, dtype: float64
----------------------------------------------------
17
322
-1    38.819876
 0     2.795031
 2     1.863354
 3     3.726708
 4     3.105590
 5    18.012422
 6    31.677019
Name: day_or_month_for_breast_feeding, dtype: float64
----------------------------------------------------
18
135
-1     65.925926
 0      1.481481
 1      0.740741
 2      0.740741
 3      3.703704
 4      2.222222
 5      1.481481
 6     12.592593
 7      2.222222
 9      1.481481
 10     0.740741
 11     0.740741
 15     2.222222
 16     1.481481
 20     1.481481
 40     0.740741
Name: day_or_month_for_breast_feeding, dtype: float64
----------------------------------------------------
19
247
-1     69.230769
 0      0.809717
 1      1.619433
 2      0.404858
 3      0.404858
 4      0.809717
 5      2.429150
 6     16.194332
 7      2.024291
 9      0.404858
 11     0.404858
 12     2.429150
 14     0.404858
 15     1.214575
 20     0.809717
 22     0.404858
Name: day_or_month_for_breast_feeding, dtype: float64
----------------------------------------------------
20
219
-1     64.383562
 0      1.369863
 1      0.913242
 2      1.826484
 3      1.826484
 4      1.369863
 5      2.283105
 6     13.698630
 7      0.456621
 9      0.913242
 10     1.369863
 12     4.109589
 13     2.283105
 14     0.913242
 22     0.456621
 23     0.456621
 24     1.369863
Name: day_or_month_for_breast_feeding, dtype: float64
----------------------------------------------------
21
352
-1     51.420455
 0      1.136364
 1      0.568182
 2      0.852273
 3      0.568182
 4      1.988636
 5      3.977273
 6     21.875000
 7      0.852273
 8      1.420455
 9      2.556818
 10     2.840909
 11     1.704545
 12     5.397727
 13     1.136364
 14     0.568182
 18     0.568182
 20     0.284091
 22     0.284091
Name: day_or_month_for_breast_feeding, dtype: float64
----------------------------------------------------
22
270
-1     58.888889
 0      1.481481
 1      0.370370
 3      0.370370
 4      1.481481
 5      0.740741
 6     22.592593
 7      5.925926
 8      1.111111
 9      0.740741
 10     1.481481
 16     0.740741
 18     0.370370
 20     0.370370
 22     1.481481
 28     1.481481
 30     0.370370
Name: day_or_month_for_breast_feeding, dtype: float64
----------------------------------------------------
23
477
-1     52.830189
 0      1.048218
 2      0.628931
 3      0.628931
 4      0.628931
 5      2.515723
 6     26.415094
 7      3.354298
 8      1.677149
 9      3.983229
 10     1.886792
 11     1.467505
 12     1.467505
 13     0.419287
 14     0.209644
 15     0.209644
 16     0.209644
 20     0.209644
 99     0.209644
Name: day_or_month_for_breast_feeding, dtype: float64
----------------------------------------------------
24
312
-1     64.102564
 0      2.884615
 3      0.320513
 4      0.320513
 5      6.730769
 6     17.628205
 7      1.282051
 10     0.641026
 12     1.282051
 13     2.564103
 14     0.961538
 20     0.961538
 26     0.320513
Name: day_or_month_for_breast_feeding, dtype: float64
----------------------------------------------------
25
235
-1     68.936170
 0      0.851064
 4      0.425532
 6     12.765957
 7      0.425532
 9      0.425532
 10     0.851064
 11     0.851064
 12     2.127660
 13     1.702128
 14     7.234043
 15     2.127660
 16     0.851064
 18     0.425532
Name: day_or_month_for_breast_feeding, dtype: float64
----------------------------------------------------
26
471
-1     44.798301
 0      2.547771
 1      1.061571
 2      1.061571
 3      1.698514
 4      1.910828
 5      5.095541
 6     24.628450
 7      4.246285
 8      3.184713
 9      0.849257
 10     4.033970
 11     1.273885
 12     2.335456
 13     0.424628
 15     0.212314
 20     0.212314
 22     0.212314
 23     0.212314
Name: day_or_month_for_breast_feeding, dtype: float64
----------------------------------------------------
27
290
-1     64.827586
 0      2.068966
 1      2.068966
 2      2.758621
 3      1.724138
 4      1.034483
 5      0.344828
 6     13.793103
 7      4.137931
 8      0.689655
 10     0.689655
 11     0.689655
 12     1.034483
 13     0.344828
 15     1.034483
 16     0.689655
 18     0.344828
 20     0.344828
 22     1.034483
 28     0.344828
Name: day_or_month_for_breast_feeding, dtype: float64
----------------------------------------------------
28
289
-1     57.439446
 0      1.730104
 1      0.346021
 2      0.346021
 4      0.346021
 5      2.422145
 6     27.681661
 7      1.384083
 9      0.346021
 10     0.692042
 11     0.346021
 12     2.076125
 13     1.730104
 15     0.692042
 20     1.038062
 22     0.692042
 23     0.346021
 24     0.346021
Name: day_or_month_for_breast_feeding, dtype: float64
----------------------------------------------------
29
457
-1     54.923414
 0      1.969365
 1      0.875274
 3      1.531729
 4      1.094092
 5      1.094092
 6     21.006565
 7      1.094092
 8      0.875274
 9      1.312910
 10     0.875274
 11     0.875274
 12     3.719912
 13     2.188184
 14     0.656455
 15     1.312910
 16     1.312910
 17     0.218818
 18     1.750547
 20     0.437637
 21     0.218818
 22     0.218818
 24     0.437637
Name: day_or_month_for_breast_feeding, dtype: float64
----------------------------------------------------
30
199
-1     62.311558
 0      4.020101
 2      2.010050
 3      4.020101
 4      1.005025
 5      1.005025
 6     22.613065
 7      1.005025
 8      1.005025
 11     0.502513
 12     0.502513
Name: day_or_month_for_breast_feeding, dtype: float64
----------------------------------------------------
31
285
-1     37.192982
 0      0.350877
 1      4.210526
 2      1.754386
 3      2.456140
 4      5.964912
 5     36.140351
 6     11.578947
 15     0.350877
Name: day_or_month_for_breast_feeding, dtype: float64
----------------------------------------------------
32
311
-1     47.909968
 0      1.607717
 1      0.643087
 2      1.286174
 3      2.250804
 4      1.929260
 5      4.501608
 6     27.009646
 7      2.572347
 8      0.964630
 9      0.964630
 10     1.286174
 11     0.964630
 12     0.643087
 13     0.643087
 14     0.321543
 16     1.607717
 18     0.964630
 20     1.286174
 23     0.321543
 33     0.321543
Name: day_or_month_for_breast_feeding, dtype: float64
----------------------------------------------------
33
267
-1     68.164794
 0      0.374532
 1      0.374532
 2      0.749064
 3      1.123596
 4      0.374532
 5      2.996255
 6     22.846442
 7      1.498127
 8      1.123596
 11     0.374532
Name: day_or_month_for_breast_feeding, dtype: float64
----------------------------------------------------
34
201
-1    18.905473
 1     1.990050
 2     1.990050
 3     3.482587
 4     4.975124
 5    41.791045
 6    26.865672
Name: day_or_month_for_breast_feeding, dtype: float64
----------------------------------------------------
35
349
-1    43.553009
 1     0.859599
 2     3.724928
 3     5.730659
 4    11.461318
 5    23.495702
 6    11.174785
Name: day_or_month_for_breast_feeding, dtype: float64
----------------------------------------------------
36
207
-1     25.120773
 1      0.966184
 2      7.729469
 3      7.729469
 4      9.661836
 5     27.536232
 6     20.772947
 25     0.483092
Name: day_or_month_for_breast_feeding, dtype: float64
----------------------------------------------------
37
420
-1    43.095238
 0     1.904762
 1     0.238095
 2     1.428571
 3     2.380952
 4     3.571429
 5    37.619048
 6     9.761905
Name: day_or_month_for_breast_feeding, dtype: float64
----------------------------------------------------
38
234
-1    14.529915
 0     1.282051
 1     2.991453
 2     3.418803
 3     8.974359
 4    11.111111
 5    48.717949
 6     8.547009
 8     0.427350
Name: day_or_month_for_breast_feeding, dtype: float64
----------------------------------------------------
39
251
-1    32.270916
 1     0.796813
 2     3.984064
 3     5.976096
 4     9.163347
 5    29.880478
 6    17.928287
Name: day_or_month_for_breast_feeding, dtype: float64
----------------------------------------------------
40
210
-1     28.571429
 1      2.380952
 2      3.333333
 3      8.095238
 4     11.428571
 5     28.571429
 6     16.190476
 11     0.476190
 24     0.476190
 26     0.476190
Name: day_or_month_for_breast_feeding, dtype: float64
----------------------------------------------------
41
414
-1     38.164251
 0      0.483092
 1      3.140097
 2      2.415459
 3      4.106280
 4      5.555556
 5     40.096618
 6      5.797101
 10     0.241546
Name: day_or_month_for_breast_feeding, dtype: float64
----------------------------------------------------
42
361
-1     42.382271
 1      1.385042
 2      1.108033
 3      3.601108
 4     14.404432
 5     28.254848
 6      8.310249
 21     0.277008
 25     0.277008
Name: day_or_month_for_breast_feeding, dtype: float64
----------------------------------------------------
43
285
-1    30.526316
 1     1.403509
 2     1.754386
 3     7.017544
 4    11.578947
 5    33.333333
 6    14.385965
Name: day_or_month_for_breast_feeding, dtype: float64
----------------------------------------------------

44
273
-1    36.630037
 0     0.366300
 1     1.465201
 2     3.296703
 3     2.564103
 4     6.227106
 5    36.996337
 6    12.454212
Name: day_or_month_for_breast_feeding, dtype: float64
----------------------------------------------------
45
482
-1     51.867220
 1      0.829876
 2      0.622407
 3      9.543568
 4     13.278008
 5     14.315353
 6      9.336100
 12     0.207469
Name: day_or_month_for_breast_feeding, dtype: float64
----------------------------------------------------

In [62]:
data.loc[(data['day_or_month_for_breast_feeding'] == -1), 'day_or_month_for_breast_feeding'] = 6

In [63]:
data['day_or_month_for_breast_feeding'][data[(data['day_or_month_for_breast_feeding'] == -1)].index].value_counts()

Series([], Name: day_or_month_for_breast_feeding, dtype: int64)

In [64]:
print(data['water_month'][data[data['water_month'] == -1].index].value_counts())
print(data['ani_milk_month'][data[data['ani_milk_month'] == -1].index].value_counts())
print(data['semisolid_month_or_day'][data[data['semisolid_month_or_day'] == -1].index].value_counts())
print(data['solid_month'][data[data['solid_month'] == -1].index].value_counts())
print(data['vegetables_month_or_day'][data[data['vegetables_month_or_day'] == -1].index].value_counts())

-1    6944
Name: water_month, dtype: int64
-1    6949
Name: ani_milk_month, dtype: int64
-1    6948
Name: semisolid_month_or_day, dtype: int64
-1    6961
Name: solid_month, dtype: int64
-1    6962
Name: vegetables_month_or_day, dtype: int64

In [65]:
for i in data['district_code'].unique():
    print(i)
    x = data['water_month'][data[(data['district_code'] == i) & (data['water_month'] != -1)].index].value_counts()
    print(x)
    y = x[x == x.max()].index.tolist()
    print(y[0])
    data.loc[((data['district_code'] == i) & (data['water_month'] == -1)), 'water_month'] = y[0]

1
5     99
6     91
7     62
0     31
4      9
3      6
9      2
10     1
8      1
Name: water_month, dtype: int64
5
2
5     36
0     27
7     13
6     12
9      5
12     1
10     1
8      1
4      1
1      1
Name: water_month, dtype: int64
5
3
5     58
0     24
7     10
1     10
11     7
8      5
9      4
6      4
13     3
4      3
15     1
14     1
12     1
10     1
2      1
Name: water_month, dtype: int64
5
4
6     65
7     33
5     28
0     18
8      9
9      4
4      4
10     3
1      2
16     1
2      1
Name: water_month, dtype: int64
6
5
0    32
5    26
7    17
6    13
1     4
8     2
9     1
Name: water_month, dtype: int64
0
6
6     72
5     69
0     21
7     12
8      9
4      8
3      5
10     4
2      3
1      3
9      2
12     1
11     1
Name: water_month, dtype: int64
6
7
5     64
0     34
7     28
9     17
8      6
6      6
3      6
2      3
1      3
4      2
10     1
Name: water_month, dtype: int64
5
8
6    126
7     46
8     17
0     16
5      7
3      7
4      6
9      1
Name: water_month, dtype: int64
6
9
7    92
6    90
0    28
5    15
8     9
4     3
3     2
9     1
Name: water_month, dtype: int64
7
10
6     88
7     38
0     30
5      6
8      5
3      5
4      3
10     1
Name: water_month, dtype: int64
6
11
6    118
7     68
0     37
5     25
8      7
4      7
3      4
9      3
Name: water_month, dtype: int64
6
12
6    167
7     35
0     22
5     20
4      9
3      9
8      4
9      2
1      1
Name: water_month, dtype: int64
6
13
0    54
7    48
6    34
8    22
9     3
5     3
Name: water_month, dtype: int64
0
14
5    44
0    36
6    33
7    16
4    12
3     1
Name: water_month, dtype: int64
5
15
6    135
0     35
7     19
5      6
8      5
9      1
4      1
Name: water_month, dtype: int64
6
16
6    116
7     59
0     43
5     11
8      2
Name: water_month, dtype: int64
6
17
7    78
6    63
0    38
8     8
5     3
4     3
3     3
9     1
Name: water_month, dtype: int64
7
18
5    21
0     7
6     6
7     5
9     1
8     1
4     1
3     1
2     1
Name: water_month, dtype: int64
5
19
5    30
6    15
7    12
0     8
9     3
4     3
1     3
2     2
Name: water_month, dtype: int64
5
20
5     37
0      9
14     5
13     5
6      4
4      4
15     2
11     2
10     2
7      2
12     1
3      1
2      1
1      1
Name: water_month, dtype: int64
5
21
5     78
6     25
0     15
7     13
4     10
11     6
13     5
12     5
14     3
9      3
10     2
8      2
3      1
2      1
1      1
Name: water_month, dtype: int64
5
22
7     39
5     37
6     12
0     10
9      8
10     2
8      2
4      1
2      1
Name: water_month, dtype: int64
7
23
5     110
10     17
0      16
7      15
6      15
8      13
12     11
9      11
11      6
3       3
13      2
4       2
15      1
14      1
2       1
Name: water_month, dtype: int64
5
24
7    35
5    33
6    32
0     9
8     2
9     1
Name: water_month, dtype: int64
7
25
5     40
6     22
0      3
13     2
16     1
15     1
14     1
12     1
8      1
4      1
Name: water_month, dtype: int64
5
26
7     77
5     51
6     28
0     26
8     19
9     12
11    10
10     9
4      9
12     7
1      5
13     2
3      2
2      2
14     1
Name: water_month, dtype: int64
7
27
5    38
0    23
7    17
6     9
1     9
8     3
9     2
4     1
Name: water_month, dtype: int64
5
28
5     82
0     10
6      8
7      4
13     3
9      3
1      3
14     2
12     2
3      2
16     1
15     1
11     1
10     1
Name: water_month, dtype: int64
5
29
5     74
6     50
0     22
7     16
1     13
8     11
3     11
12     4
10     3
9      3
4      3
2      2
Name: water_month, dtype: int64
5
30
5    45
0    18
6     7
7     3
8     1
4     1
Name: water_month, dtype: int64
5
31
6    90
0    37
7    20
5    13
8     9
4     6
3     4
Name: water_month, dtype: int64
6
32
5     57
6     27
7     26
0     26
1      7
8      4
4      4
10     3
9      3
12     2
20     1
11     1
2      1
Name: water_month, dtype: int64
5
33
5    52
7    11
8     6
9     5
6     4
0     4
4     1
1     1
Name: water_month, dtype: int64
5
34
6    71
7    44
0    37
5     5
8     4
9     2
Name: water_month, dtype: int64
6
35
6    68
0    44
5    29
7    27
4    12
3     9
9     6
8     2
Name: water_month, dtype: int64
6
36
6    49
7    34
0    22
5    18
4    13
8    10
3     8
9     1
Name: water_month, dtype: int64
6
37
6    135
0     48
7     32
5      9
8      7
4      4
3      4
Name: water_month, dtype: int64
6
38
6    112
0     41
5     16
7     15
4      9
8      4
3      3
Name: water_month, dtype: int64
6
39
6    72
7    37
0    31
5    19
4     7
8     3
3     1
Name: water_month, dtype: int64
6
40
6    42
0    41
7    34
5    14
8    10
4     7
3     2
Name: water_month, dtype: int64
6
41
6    160
0     44
7     18
5     15
4     11
3      7
8      1
Name: water_month, dtype: int64
6
42
6    99
5    37
7    33
0    33
4     3
8     2
3     1
Name: water_month, dtype: int64
6
43
6    90
7    38
5    27
0    25
4    14
8     3
3     1
Name: water_month, dtype: int64
6
44
6    100
0     28
7     26
5     12
8      4
9      1
4      1
3      1
Name: water_month, dtype: int64
6
45
6    61
5    48
4    42
0    41
7    40
Name: water_month, dtype: int64
6

In [66]:
for i in data['district_code'].unique():
    x = data['water_month'][data[(data['district_code'] == i) & (data['water_month'] != -1)].index].value_counts()
    y = x[x == x.max()].index.tolist()
    data['water_month'] = data['water_month'].fillna(y[0])

In [67]:
for i in data['district_code'].unique():
    print(i)
    x = data['ani_milk_month'][data[(data['district_code'] == i) & (data['ani_milk_month'] != -1)].index].value_counts()
    print(x)
    y = x[x == x.max()].index.tolist()
    print(y[0])
    data.loc[((data['district_code'] == i) & (data['ani_milk_month'] == -1)), 'ani_milk_month'] = y[0]

1
6     116
7      54
0      41
8      33
9      25
5      16
4      10
10      4
12      2
3       1
Name: ani_milk_month, dtype: int64
6
2
6     32
0     30
9     16
7     10
12     4
14     1
11     1
10     1
5      1
4      1
1      1
Name: ani_milk_month, dtype: int64
6
3
6     59
0     26
1     10
12     7
10     6
7      6
8      5
9      4
15     2
14     2
11     2
4      2
18     1
2      1
Name: ani_milk_month, dtype: int64
6
4
9     37
7     35
0     32
6     28
8     24
12     3
14     2
3      2
1      2
11     1
10     1
5      1
Name: ani_milk_month, dtype: int64
9
5
0     38
6     24
9     16
8      6
12     3
10     3
1      3
7      1
3      1
Name: ani_milk_month, dtype: int64
0
6
6     66
8     38
7     31
0     27
9     16
10    11
12     9
4      3
15     2
5      2
1      2
27     1
17     1
13     1
Name: ani_milk_month, dtype: int64
6
7
6     59
0     49
9     17
8     13
12     7
7      6
10     4
4      4
3      4
11     3
2      2
16     1
1      1
Name: ani_milk_month, dtype: int64
6
8
6     96
8     39
7     38
0     24
9     11
4      7
5      6
10     4
12     1
Name: ani_milk_month, dtype: int64
6
9
7    74
8    59
6    56
0    31
5    11
9     7
4     2
Name: ani_milk_month, dtype: int64
7
10
6     63
7     35
0     33
8     29
9      6
4      5
5      4
13     1
Name: ani_milk_month, dtype: int64
6
11
6     83
7     65
8     52
0     52
5      6
4      6
9      4
10     1
Name: ani_milk_month, dtype: int64
6
12
6    101
7     72
0     41
8     33
5     10
4      8
9      4
Name: ani_milk_month, dtype: int64
6
13
0    60
8    44
7    37
6    18
9     3
5     2
Name: ani_milk_month, dtype: int64
0
14
7     39
0     39
8     17
6     16
5     16
9      8
10     6
12     1
Name: ani_milk_month, dtype: int64
7
15
6     66
7     49
0     37
8     29
5     10
10     5
9      5
11     1
Name: ani_milk_month, dtype: int64
6
16
7     124
0      44
6      43
8       9
5       3
10      2
3       2
9       1
2       1
Name: ani_milk_month, dtype: int64
7
17
7     71
8     47
0     45
6     17
9     12
10     5
Name: ani_milk_month, dtype: int64
7
18
6     16
0     12
9      6
7      6
8      3
12     1
Name: ani_milk_month, dtype: int64
6
19
6     30
7     18
0     11
9      4
12     3
8      3
5      2
4      2
1      2
2      1
Name: ani_milk_month, dtype: int64
6
20
6     35
0     15
14     6
7      5
15     3
12     3
16     2
11     2
9      2
13     1
8      1
Name: ani_milk_month, dtype: int64
6
21
6     79
0     27
7     20
8     12
13     6
12     5
15     4
14     4
9      4
10     3
11     2
5      2
4      1
3      1
Name: ani_milk_month, dtype: int64
6
22
6     35
9     24
0     21
8     15
12     7
10     4
7      4
16     1
11     1
Name: ani_milk_month, dtype: int64
6
23
6     113
0      19
7      17
11     14
12     12
10     12
8      12
9      10
13      5
14      3
15      2
4       2
5       1
2       1
Name: ani_milk_month, dtype: int64
6
24
8     29
6     26
9     22
7     21
0     10
11     2
10     1
5      1
Name: ani_milk_month, dtype: int64
8
25
6     40
8     16
7      7
0      4
15     2
14     2
12     1
10     1
Name: ani_milk_month, dtype: int64
6
26
6     61
7     47
8     40
0     39
9     17
10    14
12    11
11     9
4      7
13     4
5      3
1      3
15     2
14     2
18     1
Name: ani_milk_month, dtype: int64
6
27
6     37
0     30
9     13
1      9
7      5
8      4
13     2
12     1
10     1
Name: ani_milk_month, dtype: int64
6
28
6     80
0     12
7      7
15     3
14     3
12     3
9      3
1      3
13     2
11     2
5      2
17     1
8      1
4      1
Name: ani_milk_month, dtype: int64
6
29
6     81
0     54
7     25
8     14
1     10
10     6
9      6
12     4
5      2
4      2
3      2
2      2
16     1
15     1
14     1
Name: ani_milk_month, dtype: int64
6
30
6    42
0    24
7     5
9     3
8     1
Name: ani_milk_month, dtype: int64
6
31
6     62
0     43
7     29
5     13
8     12
4      6
9      5
3      5
10     2
12     1
2      1
Name: ani_milk_month, dtype: int64
6
32
6     57
0     37
7     28
9     11
8      8
1      7
12     3
10     3
14     2
5      2
20     1
17     1
16     1
4      1
Name: ani_milk_month, dtype: int64
6
33
6     47
0     14
8      7
12     6
9      5
7      3
11     1
1      1
Name: ani_milk_month, dtype: int64
6
34
7    58
0    43
6    40
8    19
9     3
Name: ani_milk_month, dtype: int64
7
35
6     71
0     47
7     31
5     17
8     11
4     11
10     5
9      4
Name: ani_milk_month, dtype: int64
6
36
6     32
7     29
0     28
5     16
4     11
8      9
14     6
9      5
18     4
12     4
16     2
24     2
25     1
11     1
15     1
19     1
21     1
22     1
13     1
Name: ani_milk_month, dtype: int64
6
37
7     111
0      57
6      33
8      15
5      11
9       6
4       4
10      1
1       1
Name: ani_milk_month, dtype: int64
7
38
6    55
7    53
0    43
8    18
9    12
5    10
4     6
3     3
Name: ani_milk_month, dtype: int64
6
39
0    51
6    49
7    46
5    12
8    11
4     1
Name: ani_milk_month, dtype: int64
0
40
0    46
7    36
6    36
8    21
5     9
4     2
Name: ani_milk_month, dtype: int64
0
41
7    85
0    61
6    47
8    18
4    14
5    13
2    12
3     6
Name: ani_milk_month, dtype: int64
7
42
7    77
0    45
6    40
8    27
5    12
9     3
4     3
3     1
Name: ani_milk_month, dtype: int64
7
43
6     85
7     46
0     26
5     20
4     13
9      4
10     3
8      1
Name: ani_milk_month, dtype: int64
6
44
7    56
6    56
0    42
8    12
9     5
5     1
4     1
Name: ani_milk_month, dtype: int64
7
45
6    68
7    53
5    41
0    41
4    20
8     9
Name: ani_milk_month, dtype: int64
6

In [68]:
for i in data['district_code'].unique():
    x = data['ani_milk_month'][data[(data['district_code'] == i) & (data['ani_milk_month'] != -1)].index].value_counts()
    y = x[x == x.max()].index.tolist()
    data['ani_milk_month'] = data['ani_milk_month'].fillna(y[0])

In [69]:
for i in data['district_code'].unique():
    print(i)
    x = data['semisolid_month_or_day'][data[(data['district_code'] == i) & (data['semisolid_month_or_day'] != -1)].index].value_counts()
    print(x)
    y = x[x == x.max()].index.tolist()
    print(y[0])
    data.loc[((data['district_code'] == i) & (data['semisolid_month_or_day'] == -1)), 'semisolid_month_or_day'] = y[0]

1
6     83
9     51
0     49
10    38
7     35
8     26
12     7
11     5
5      5
4      2
15     1
Name: semisolid_month_or_day, dtype: int64
6
2
0     32
6     22
10    13
12     9
16     6
9      5
14     3
18     2
7      2
13     1
11     1
8      1
1      1
Name: semisolid_month_or_day, dtype: int64
0
3
6     53
0     30
1     10
10     7
9      5
8      5
12     4
15     3
14     3
13     3
11     3
16     2
7      2
20     1
18     1
5      1
Name: semisolid_month_or_day, dtype: int64
6
4
0     41
10    33
9     26
6     20
12    17
8     13
11     6
16     4
7      3
26     1
19     1
18     1
14     1
1      1
Name: semisolid_month_or_day, dtype: int64
0
5
0     38
6     22
10    15
9      6
15     5
8      3
12     2
1      2
16     1
7      1
Name: semisolid_month_or_day, dtype: int64
0
6
6     53
9     32
8     31
0     29
12    18
10    16
7     12
11     5
16     3
18     2
17     2
13     2
1      2
15     1
14     1
5      1
Name: semisolid_month_or_day, dtype: int64
6
7
0     60
6     54
10    16
9     11
7     10
16     6
12     4
14     2
8      2
20     1
18     1
13     1
3      1
1      1
Name: semisolid_month_or_day, dtype: int64
0
8
6     49
7     46
8     40
0     30
10    26
9     20
12     8
5      7
Name: semisolid_month_or_day, dtype: int64
6
9
8     83
9     52
0     41
7     26
6     21
10    14
5      2
11     1
Name: semisolid_month_or_day, dtype: int64
8
10
0     41
7     38
6     37
8     25
9     22
5      6
11     3
10     3
13     1
Name: semisolid_month_or_day, dtype: int64
0
11
8     90
0     55
7     44
6     39
9     24
10    12
5      4
11     1
Name: semisolid_month_or_day, dtype: int64
8
12
8     79
0     67
7     49
6     35
9     28
5      9
10     2
Name: semisolid_month_or_day, dtype: int64
8
13
0    62
8    42
7    28
9    18
6    12
5     2
Name: semisolid_month_or_day, dtype: int64
0
14
0     46
8     39
10    24
9     14
6      6
7      4
15     3
11     3
12     2
13     1
Name: semisolid_month_or_day, dtype: int64
0
15
0     49
6     37
8     35
9     28
7     22
10    15
11    14
5      2
Name: semisolid_month_or_day, dtype: int64
0
16
7     61
8     57
0     48
9     45
6     15
10     2
14     1
12     1
11     1
Name: semisolid_month_or_day, dtype: int64
7
17
8     74
0     49
9     37
10    11
6     11
7     10
12     2
11     2
Name: semisolid_month_or_day, dtype: int64
8
18
0     14
6     12
10     8
12     5
9      3
14     1
11     1
Name: semisolid_month_or_day, dtype: int64
0
19
6     26
9     13
0     12
10     9
8      9
16     3
1      2
7      1
2      1
Name: semisolid_month_or_day, dtype: int64
6
20
6     27
0     15
9      7
15     5
7      5
12     4
8      4
17     2
16     2
14     2
18     1
13     1
Name: semisolid_month_or_day, dtype: int64
6
21
6     56
0     32
9     25
10    12
7     12
8      6
15     5
14     5
12     4
16     3
13     3
11     3
20     1
18     1
17     1
3      1
Name: semisolid_month_or_day, dtype: int64
6
22
6     33
0     23
10    16
12    10
16     5
11     5
9      5
14     4
18     3
17     2
7      2
19     1
15     1
13     1
8      1
Name: semisolid_month_or_day, dtype: int64
6
23
6     106
12     22
0      21
8      13
13     11
9      11
7      11
11      8
10      8
15      6
14      5
16      1
Name: semisolid_month_or_day, dtype: int64
6
24
9     35
6     25
10    18
0     10
11     5
17     3
16     3
14     3
12     3
8      3
20     1
19     1
18     1
2      1
Name: semisolid_month_or_day, dtype: int64
9
25
6     29
9     24
10     6
11     5
15     3
0      3
18     1
16     1
7      1
Name: semisolid_month_or_day, dtype: int64
6
26
0     44
6     42
8     40
9     37
7     29
10    21
12    19
13    10
11     5
15     4
18     3
14     3
1      2
16     1
Name: semisolid_month_or_day, dtype: int64
0
27
0     33
6     32
10     9
1      9
12     5
16     4
8      4
14     3
18     1
17     1
7      1
Name: semisolid_month_or_day, dtype: int64
0
28
6     74
0     14
10     7
9      7
18     4
16     3
7      3
1      3
15     2
14     2
17     1
12     1
11     1
8      1
Name: semisolid_month_or_day, dtype: int64
6
29
6     80
0     28
9     25
10    16
12    14
7     12
8     10
5      9
1      8
11     3
13     2
15     1
4      1
3      1
2      1
Name: semisolid_month_or_day, dtype: int64
6
30
6     37
0     24
8      7
10     3
9      2
7      2
Name: semisolid_month_or_day, dtype: int64
6
31
0     55
7     33
9     31
8     29
6     18
10     8
12     4
5      1
Name: semisolid_month_or_day, dtype: int64
0
32
0     42
6     38
8     17
9     15
10    14
7     12
1      7
12     6
16     2
15     2
14     2
20     1
19     1
18     1
11     1
5      1
Name: semisolid_month_or_day, dtype: int64
0
33
6     39
0     13
10     8
7      8
12     5
9      3
8      3
16     2
15     1
11     1
1      1
Name: semisolid_month_or_day, dtype: int64
6
34
0     53
8     52
7     31
6     18
9      8
10     1
Name: semisolid_month_or_day, dtype: int64
0
35
7     54
0     51
6     35
8     31
10    11
5      9
9      5
11     1
Name: semisolid_month_or_day, dtype: int64
7
36
0     34
7     27
9     23
8     19
11    14
6      7
14     5
12     4
18     4
5      4
22     3
16     2
15     2
24     2
25     1
13     1
21     1
23     1
26     1
Name: semisolid_month_or_day, dtype: int64
0
37
8     109
0      60
7      28
6      19
9      14
10      4
5       4
1       1
Name: semisolid_month_or_day, dtype: int64
8
38
7     55
0     52
8     46
9     22
10    15
12     4
6      4
11     2
Name: semisolid_month_or_day, dtype: int64
7
39
8     78
0     44
7     24
6     16
10     5
9      2
5      1
Name: semisolid_month_or_day, dtype: int64
8
40
0     59
8     38
7     17
10    12
6     11
9      9
12     3
11     1
Name: semisolid_month_or_day, dtype: int64
0
41
8    111
0     76
7     27
6     24
9     13
5      5
Name: semisolid_month_or_day, dtype: int64
8
42
8     74
0     46
9     28
7     24
10    19
6      8
5      6
11     3
Name: semisolid_month_or_day, dtype: int64
8
43
8     59
7     57
0     34
9     25
6     14
10     4
11     3
12     1
5      1
Name: semisolid_month_or_day, dtype: int64
8
44
8     54
0     44
7     38
6     18
10    10
9      7
11     1
5      1
Name: semisolid_month_or_day, dtype: int64
8
45
7    74
8    48
0    41
6    40
5    21
9     8
Name: semisolid_month_or_day, dtype: int64
7

In [70]:
for i in data['district_code'].unique():
    x = data['semisolid_month_or_day'][data[(data['district_code'] == i) & (data['semisolid_month_or_day'] != -1)].index].value_counts()
    y = x[x == x.max()].index.tolist()
    data['semisolid_month_or_day'] = data['semisolid_month_or_day'].fillna(y[0])

In [71]:
for i in data['district_code'].unique():
    print(i)
    x = data['solid_month'][data[(data['district_code'] == i) & (data['solid_month'] != -1)].index].value_counts()
    print(x)
    y = x[x == x.max()].index.tolist()
    print(y[0])
    data.loc[((data['district_code'] == i) & (data['solid_month'] == -1)), 'solid_month'] = y[0]

1
7     75
0     63
12    49
10    35
11    32
9     15
8     11
6     10
14     5
13     2
5      2
16     1
15     1
4      1
Name: solid_month, dtype: int64
7
2
0     33
7     22
11    11
12     5
23     3
22     3
20     3
10     3
26     2
25     2
14     2
1      1
9      1
32     1
15     1
30     1
24     1
28     1
29     1
18     1
Name: solid_month, dtype: int64
0
3
7     52
0     33
1     10
12     8
18     7
10     7
8      4
14     3
24     2
15     2
20     1
17     1
16     1
11     1
9      1
Name: solid_month, dtype: int64
7
4
0     51
12    39
7     20
10    18
11    12
9      8
15     6
14     2
13     2
8      2
22     1
17     1
16     1
25     1
6      1
1      1
26     1
Name: solid_month, dtype: int64
0
5
0     40
7     22
12    15
15     9
10     3
20     1
19     1
16     1
11     1
9      1
1      1
Name: solid_month, dtype: int64
0
6
7     54
0     38
12    32
10    21
9     18
14    12
8      7
15     6
13     5
11     3
18     2
16     2
20     2
1      2
26     1
19     1
22     1
25     1
27     1
Name: solid_month, dtype: int64
7
7
0     73
7     50
12    23
9      3
14     3
24     2
20     2
18     2
8      2
28     2
10     2
1      1
92     1
17     1
22     1
26     1
16     1
Name: solid_month, dtype: int64
0
8
12    48
8     43
7     40
0     34
9     23
10    16
11    11
6     10
13     1
Name: solid_month, dtype: int64
12
9
8     61
9     51
0     45
10    29
7     26
11    14
12    10
6      4
Name: solid_month, dtype: int64
8
10
0     47
8     33
7     33
6     24
9     17
10    12
11     8
18     1
5      1
Name: solid_month, dtype: int64
0
11
0     70
8     58
7     44
10    29
9     28
11    16
12    15
6      9
Name: solid_month, dtype: int64
0
12
0     69
9     61
8     57
7     45
10    22
6     13
13     1
12     1
Name: solid_month, dtype: int64
0
13
0     62
8     44
7     24
10    13
9     11
6      8
5      2
Name: solid_month, dtype: int64
0
14
0     55
10    42
12    12
11    12
9     10
8      6
24     2
20     1
18     1
15     1
Name: solid_month, dtype: int64
0
15
0     53
11    42
7     35
8     29
9     18
10    17
6      5
12     2
13     1
Name: solid_month, dtype: int64
0
16
0     61
9     49
8     48
10    37
7     16
12    12
11     4
14     2
16     1
Name: solid_month, dtype: int64
0
17
9     58
0     52
10    38
8     27
7     13
11     6
15     1
14     1
12     1
Name: solid_month, dtype: int64
9
18
0     14
7     12
12     7
16     3
11     3
26     2
14     2
1      1
Name: solid_month, dtype: int64
0
19
7     26
12    15
0     13
14     4
18     3
11     3
10     3
9      3
22     2
1      2
20     1
2      1
Name: solid_month, dtype: int64
7
20
7     26
0     22
18     5
9      5
16     4
15     4
12     2
11     2
10     2
17     1
14     1
6      1
Name: solid_month, dtype: int64
7
21
7     55
0     45
12    14
15     9
14     8
18     6
11     6
9      6
16     5
10     5
17     3
13     2
8      2
2      2
1      1
Name: solid_month, dtype: int64
7
22
7     33
0     31
12    12
11     6
10     5
21     5
26     2
23     2
22     2
27     2
16     2
14     1
28     1
17     1
20     1
24     1
25     1
18     1
Name: solid_month, dtype: int64
7
23
7     104
0      25
15     19
13     13
9      13
12      9
10      9
16      7
14      7
8       6
18      4
11      4
6       1
Name: solid_month, dtype: int64
7
24
11    26
7     25
12    21
0     15
21     5
10     5
13     2
22     2
9      2
14     2
26     1
25     1
17     1
18     1
20     1
24     1
16     1
Name: solid_month, dtype: int64
11
25
7     29
12    20
11     8
14     5
0      3
18     2
16     2
15     1
13     1
10     1
9      1
Name: solid_month, dtype: int64
7
26
0     57
7     45
9     36
12    22
11    22
10    20
15    16
8     15
14    11
18     7
16     2
13     2
1      2
22     1
19     1
6      1
Name: solid_month, dtype: int64
0
27
0     36
7     31
1      9
12     7
18     3
14     3
25     2
23     2
22     2
8      2
6      2
26     1
21     1
10     1
Name: solid_month, dtype: int64
0
28
7     74
0     15
11     6
16     5
18     4
12     3
8      3
1      3
21     2
15     2
10     2
20     1
17     1
14     1
9      1
Name: solid_month, dtype: int64
7
29
7     66
0     40
12    22
8     19
10    14
11     9
6      8
1      8
9      5
15     4
20     3
18     3
16     2
13     1
14     1
2      1
24     1
Name: solid_month, dtype: int64
7
30
7     36
0     24
12     8
8      3
10     2
9      2
Name: solid_month, dtype: int64
7
31
0     68
9     40
8     16
7     16
10    14
12    10
11     7
6      4
14     2
13     2
Name: solid_month, dtype: int64
0
32
0     56
7     35
12    17
10     8
1      7
8      6
11     6
14     6
9      5
16     4
20     3
6      2
22     2
13     1
23     1
15     1
5      1
25     1
Name: solid_month, dtype: int64
0
33
7     39
0     20
12    11
10     3
9      3
15     2
1      2
20     1
19     1
16     1
11     1
Name: solid_month, dtype: int64
7
34
0     64
7     34
8     17
12    14
10    11
11    10
9      7
6      5
14     1
Name: solid_month, dtype: int64
0
35
0     56
7     55
9     30
8     28
10    15
6      9
15     2
12     1
11     1
Name: solid_month, dtype: int64
0
36
0     58
12    19
9     16
8     14
7     11
11    10
14     5
18     4
6      4
22     3
16     2
15     2
24     2
25     1
13     1
21     1
23     1
26     1
Name: solid_month, dtype: int64
0
37
9     88
0     73
8     40
7     18
10     8
6      6
14     3
11     1
1      1
Name: solid_month, dtype: int64
9
38
0     62
8     45
9     37
10    30
7     19
12     6
11     1
Name: solid_month, dtype: int64
0
39
0     55
8     40
10    18
11    14
7     14
12    12
9     10
6      7
Name: solid_month, dtype: int64
0
40
0     66
8     34
9     11
10    10
11     9
7      8
6      7
12     5
Name: solid_month, dtype: int64
0
41
9     103
0      82
8      29
7      25
6       6
10      5
11      4
19      1
3       1
Name: solid_month, dtype: int64
9
42
8     58
0     56
9     55
11    19
10    12
5      4
12     2
7      2
Name: solid_month, dtype: int64
8
43
9     96
0     41
8     23
7     20
11     9
6      4
13     2
12     2
14     1
Name: solid_month, dtype: int64
9
44
0     48
7     36
8     26
10    25
9     17
11     8
12     7
6      4
13     1
2      1
Name: solid_month, dtype: int64
0
45
8    69
7    52
9    47
0    43
6    21
Name: solid_month, dtype: int64
8

In [72]:
for i in data['district_code'].unique():
    x = data['solid_month'][data[(data['district_code'] == i) & (data['solid_month'] != -1)].index].value_counts()
    y = x[x == x.max()].index.tolist()
    data['solid_month'] = data['solid_month'].fillna(y[0])

In [73]:
for i in data['district_code'].unique():
    print(i)
    x = data['vegetables_month_or_day'][data[(data['district_code'] == i) & (data['vegetables_month_or_day'] != -1)].index].value_counts()
    print(x)
    y = x[x == x.max()].index.tolist()
    print(y[0])
    data.loc[((data['district_code'] == i) & (data['vegetables_month_or_day'] == -1)), 'vegetables_month_or_day'] = y[0]

1
8     75
0     63
12    35
13    34
10    33
11    14
7     13
9     10
6      9
14     5
15     3
18     2
16     2
5      1
4      1
2      1
20     1
Name: vegetables_month_or_day, dtype: int64
8
2
0     36
8     22
10    16
24     4
16     2
29     2
27     2
26     2
12     2
9      1
11     1
34     1
18     1
21     1
33     1
25     1
28     1
32     1
22     1
Name: vegetables_month_or_day, dtype: int64
0
3
8     52
0     43
12    10
18     6
10     5
15     3
22     2
20     2
14     2
9      1
1      1
6      1
26     1
11     1
24     1
16     1
13     1
Name: vegetables_month_or_day, dtype: int64
8
4
0     53
10    39
12    25
8     21
11     7
15     6
14     5
21     2
16     2
13     2
28     1
26     1
22     1
20     1
18     1
1      1
Name: vegetables_month_or_day, dtype: int64
0
5
0     42
8     22
10    13
15     9
14     3
11     3
12     2
25     1
Name: vegetables_month_or_day, dtype: int64
0
6
8     54
0     43
12    32
10    19
14    11
16    10
15    10
11     6
7      4
13     3
18     3
17     2
20     2
9      2
5      2
28     2
26     1
22     1
24     1
6      1
Name: vegetables_month_or_day, dtype: int64
8
7
0     77
8     49
10    19
12     8
9      4
25     3
24     2
22     2
19     2
14     2
30     1
26     1
Name: vegetables_month_or_day, dtype: int64
0
8
8     59
12    50
0     34
9     28
10    22
7     12
14     6
16     4
13     4
15     3
11     2
6      2
Name: vegetables_month_or_day, dtype: int64
8
9
9     70
0     47
10    40
8     33
11    16
12    11
7      9
14     7
13     5
17     1
15     1
Name: vegetables_month_or_day, dtype: int64
9
10
0     49
8     33
9     29
6     17
10    16
7     15
11    14
18     1
12     1
5      1
Name: vegetables_month_or_day, dtype: int64
0
11
8     75
0     72
12    37
9     33
10    24
11    16
7     11
6      1
Name: vegetables_month_or_day, dtype: int64
8
12
0     69
8     67
10    55
9     37
7     22
11    17
13     2
Name: vegetables_month_or_day, dtype: int64
0
13
0     65
8     35
9     20
7     18
11     9
6      8
10     7
5      2
Name: vegetables_month_or_day, dtype: int64
0
14
0     61
11    45
10    13
13     7
12     7
9      5
24     2
20     1
15     1
Name: vegetables_month_or_day, dtype: int64
0
15
0     53
11    48
8     39
7     18
9     17
10    15
12     7
6      3
13     2
Name: vegetables_month_or_day, dtype: int64
0
16
0     64
9     42
10    40
12    33
8     31
11    17
16     2
18     1
14     1
Name: vegetables_month_or_day, dtype: int64
0
17
10    58
0     52
9     33
11    30
8     12
7      7
12     3
15     1
14     1
Name: vegetables_month_or_day, dtype: int64
10
18
0     14
8     12
10     8
16     3
20     2
28     1
22     1
18     1
14     1
12     1
Name: vegetables_month_or_day, dtype: int64
0
19
8     26
0     19
12    14
20     3
25     2
18     2
11     2
10     2
9      2
16     1
15     1
14     1
2      1
Name: vegetables_month_or_day, dtype: int64
8
20
8     26
0     21
10     9
18     6
16     3
17     2
11     2
9      2
19     1
15     1
12     1
7      1
Name: vegetables_month_or_day, dtype: int64
8
21
8     58
0     52
10    12
18    11
12    10
16     7
14     4
11     4
15     3
17     2
9      2
19     1
13     1
5      1
2      1
Name: vegetables_month_or_day, dtype: int64
8
22
0     35
8     33
12    14
10     7
22     4
28     3
25     3
26     2
24     2
20     2
18     2
17     1
16     1
4      1
Name: vegetables_month_or_day, dtype: int64
0
23
8     104
15     26
0      26
14     12
10     12
16      7
12      7
11      7
13      6
9       6
18      4
17      2
20      1
3       1
Name: vegetables_month_or_day, dtype: int64
8
24
13    25
8     25
0     17
14    16
12    10
23     4
25     3
16     3
22     2
10     2
28     1
27     1
20     1
3      1
2      1
Name: vegetables_month_or_day, dtype: int64
13
25
8     29
14    11
10     7
11     5
18     4
13     4
15     3
0      3
17     2
16     2
12     2
4      1
Name: vegetables_month_or_day, dtype: int64
8
26
0     60
12    45
8     45
10    29
18    19
11    17
15    14
9     10
7      7
20     3
14     3
16     2
13     2
6      2
22     1
19     1
Name: vegetables_month_or_day, dtype: int64
0
27
0     47
8     33
6      4
10     3
26     2
24     2
20     2
18     2
12     2
25     1
22     1
16     1
13     1
11     1
Name: vegetables_month_or_day, dtype: int64
0
28
8     74
0     18
10     9
18     8
16     3
23     2
17     2
9      2
25     1
13     1
12     1
11     1
7      1
Name: vegetables_month_or_day, dtype: int64
8
29
8     67
0     53
12    27
10    26
15     8
18     5
13     5
24     3
16     3
9      3
20     2
22     1
14     1
11     1
7      1
Name: vegetables_month_or_day, dtype: int64
8
30
8     36
0     23
10    12
12     2
9      1
Name: vegetables_month_or_day, dtype: int64
8
31
0     69
10    25
11    23
12    21
8     12
9     10
7      9
13     7
15     1
14     1
6      1
Name: vegetables_month_or_day, dtype: int64
0
32
0     60
8     37
10    12
12    12
16     8
11     7
7      5
14     5
20     3
15     2
18     2
24     2
26     1
13     1
17     1
9      1
23     1
6      1
28     1
Name: vegetables_month_or_day, dtype: int64
0
33
8     39
0     21
10     8
15     3
12     2
11     2
9      2
3      2
24     1
22     1
21     1
19     1
1      1
Name: vegetables_month_or_day, dtype: int64
8
34
0     65
7     30
12    19
8     17
10    11
11    10
9      6
6      4
14     1
Name: vegetables_month_or_day, dtype: int64
0
35
0     59
7     51
10    33
9     24
8     18
11     7
18     2
12     2
13     1
Name: vegetables_month_or_day, dtype: int64
0
36
0     58
9     17
13    15
8     15
11     9
12     7
7      6
10     6
18     5
14     4
16     3
22     3
24     2
26     1
15     1
21     1
25     1
28     1
Name: vegetables_month_or_day, dtype: int64
0
37
0     92
10    61
8     35
9     31
7      8
11     4
14     3
6      2
12     1
Name: vegetables_month_or_day, dtype: int64
0
38
0     65
9     40
8     32
10    28
12    14
7     13
11     8
Name: vegetables_month_or_day, dtype: int64
0
39
0     55
9     34
8     20
11    18
10    18
12    17
6      5
7      3
Name: vegetables_month_or_day, dtype: int64
0
40
0     72
8     22
9     18
10    11
11     9
7      6
6      6
12     4
14     1
13     1
Name: vegetables_month_or_day, dtype: int64
0
41
0     86
9     70
10    47
8     33
11    10
7      6
6      3
19     1
Name: vegetables_month_or_day, dtype: int64
0
42
0     59
9     57
10    48
11    17
8     12
12     8
5      4
14     2
7      1
Name: vegetables_month_or_day, dtype: int64
0
43
11    74
0     47
9     32
10    13
8     12
7     12
15     3
14     3
13     2
Name: vegetables_month_or_day, dtype: int64
11
44
0     48
8     35
10    30
9     15
7     14
11    13
12     9
15     2
14     2
6      2
2      1
1      1
Name: vegetables_month_or_day, dtype: int64
0
45
8     65
9     57
0     44
10    33
7     33
Name: vegetables_month_or_day, dtype: int64
8

In [74]:
for i in data['district_code'].unique():
    x = data['vegetables_month_or_day'][data[(data['district_code'] == i) & (data['vegetables_month_or_day'] != -1)].index].value_counts()
    y = x[x == x.max()].index.tolist()
    data['vegetables_month_or_day'] = data['vegetables_month_or_day'].fillna(y[0])

In [75]:
print(data['water_month'][data[data['water_month'] == -1].index].value_counts())
print(data['ani_milk_month'][data[data['ani_milk_month'] == -1].index].value_counts())
print(data['semisolid_month_or_day'][data[data['semisolid_month_or_day'] == -1].index].value_counts())
print(data['solid_month'][data[data['solid_month'] == -1].index].value_counts())
print(data['vegetables_month_or_day'][data[data['vegetables_month_or_day'] == -1].index].value_counts())

Series([], Name: water_month, dtype: int64)
Series([], Name: ani_milk_month, dtype: int64)
Series([], Name: semisolid_month_or_day, dtype: int64)
Series([], Name: solid_month, dtype: int64)
Series([], Name: vegetables_month_or_day, dtype: int64)

In [76]:
data = data.drop('district_code', axis=1)

In [77]:
data.columns.values

array(['state_code', 'record_code_iodine', 'sex', 'age_code', 'age',
       'weight_in_kg', 'length_height_cm', 'haemoglobin_level',
       'first_breast_feeding', 'is_cur_breast_feeding',
       'day_or_month_for_breast_feeding_',
       'day_or_month_for_breast_feeding', 'water_month', 'ani_milk_month',
       'semisolid_month_or_day', 'solid_month', 'vegetables_month_or_day',
       'illness_type', 'treatment_type'], dtype=object)

In [78]:
data.shape

(14661, 19)

In [79]:
for i in data[data['day_or_month_for_breast_feeding_'] == 'D'].index:
    print(i,' ',data['day_or_month_for_breast_feeding_'][i],' ',data['day_or_month_for_breast_feeding'][i])
    if data['day_or_month_for_breast_feeding'][i] < 15:
        data['day_or_month_for_breast_feeding'][i] = 0
    else :
        data['day_or_month_for_breast_feeding'][i] = 1
    print(i,' ',data['day_or_month_for_breast_feeding_'][i],' ',data['day_or_month_for_breast_feeding'][i])

1466   D   0
1466   D   0
3612   D   0
3612   D   0
4346

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

  D   6
4346   D   0
5677   D   0
5677   D   0
6585   D   15
6585   D   1
6635   D   15
6635   D   1
8595   D   1
8595   D   0
9428   D   0
9428   D   0
9429   D   0
9429   D   0
9638   D   0
9638   D   0
9679   D   5
9679   D   0
13898   D   0
13898   D   0
14838   D   1
14838   D   0
16175   D   15
16175   D   1
18158   D   4
18158   D   0
18858   D   8
18858   D   0
19172   D   2
19172   D   0
19241   D   19
19241   D   1
20004   D   5
20004   D   0
21027   D   7
21027   D   0
23377   D   0
23377   D   0
24313   D   20
24313   D   1
24953   D   14
24953   D   0
25116   D   7
25116   D   0
27970   D   1
27970   D   0
28823   D   8
28823   D   0
32406   D   0
32406   D   0
32778   D   0
32778   D   0
33150   D   0
33150   D   0
33466   D   1
33466   D   0
34305   D   0
34305   D   0
34459   D   2
34459   D   0
35232   D   27
35232   D   1
42458   D   7
42458   D   0
44498   D   20
44498   D   1
58413   D   6
58413   D   0
58516   D   6
58516   D   0
61041   D   4
61041   D   0
70803   D   6
70803   D   0
75564   D   17
75564   D   1
78676   D   28
78676   D   1
78677   D   29
78677   D   1
78715   D   8
78715   D   0
78749   D   27
78749   D   1
78801   D   15
78801   D   1
88916   D   16
88916   D   1
92405   D   15
92405   D   1
101606   D   40
101606   D   1
106721   D   3
106721   D   0
111469   D   0
111469   D   0
111701   D   2
111701   D   0
112011   D   0
112011   D   0
113755   D   0
113755   D   0
114025   D   4
114025   D   0
115078   D   24
115078   D   1
118583   D   0
118583   D   0
119767   D   6
119767   D   0
121235   D   8
121235   D   0
121869   D   0
121869   D   0
122386   D   0
122386   D   0
123881   D   0
123881   D   0
126346   D   0
126346   D   0
127054   D   0
127054   D   0
130282   D   0
130282   D   0
133583   D   0
133583   D   0
133660   D   99
133660   D   1
133818   D   0
133818   D   0
133819   D   15
133819   D   1
134177   D   10
134177   D   0
134217   D   16
134217   D   1
135246   D   0
135246   D   0
135293   D   0
135293   D   0
135356   D   0
135356   D   0
135444   D   0
135444   D   0
135480   D   0
135480   D   0
135498   D   0
135498   D   0
136198   D   0
136198   D   0
138930   D   0
138930   D   0
140147   D   0
140147   D   0
149994   D   11
149994   D   0
150743   D   8
150743   D   0
155573   D   0
155573   D   0
155867   D   0
155867   D   0
160424   D   23
160424   D   1
160443   D   7
160443   D   0
163447   D   0
163447   D   0
164205   D   3
164205   D   0
169299   D   7
169299   D   0
173305   D   15
173305   D   1
176602   D   5
176602   D   0
180333   D   7
180333   D   0
183748   D   0
183748   D   0
183794   D   7
183794   D   0
187394   D   12
187394   D   0
208393   D   25
208393   D   1
213543   D   8
213543   D   0
223831   D   11
223831   D   0
226185   D   26
226185   D   1
227776   D   24
227776   D   1
235939   D   10
235939   D   0
236580   D   21
236580   D   1
242348   D   25
242348   D   1
257036   D   12
257036   D   0

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [ ]:
for i in data[data['age_code'] == 'Y'].index:
    x = data['age'][i]
    print(i,' ',data['age_code'][i],' ',data['age'][i])
    data['age'][i] = x*12
    print(i,' ',data['age_code'][i],' ',data['age'][i])

37   Y   1
37   Y   12
85   Y   1
85   Y   12
86   Y

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

1
86   Y   12
122   Y   3
122   Y   36
135   Y   1
135   Y   12
202   Y   2
202   Y   24
226   Y   4
226   Y   48
230   Y   4
230   Y   48
233   Y   2
233   Y   24
244   Y   4
244   Y   48
250   Y   3
250   Y   36
251   Y   2
251   Y   24
263   Y   4
263   Y   48
279   Y   5
279   Y   60
280   Y   2
280   Y   24
281   Y   2
281   Y   24
314   Y   4
314   Y   48
320   Y   5
320   Y   60
360   Y   5
360   Y   60
384   Y   2
384   Y   24
386   Y   2
386   Y   24
392   Y   1
392   Y   12
501   Y   2
501   Y   24
535   Y   3
535   Y   36
573   Y   3
573   Y   36
588   Y   3
588   Y   36
603   Y   3
603   Y   36
626   Y   4
626   Y   48
661   Y   3
661   Y   36
677   Y   4
677   Y   48
719   Y   3
719   Y   36
744   Y   4
744   Y   48
752   Y   1
752   Y   12
753   Y   4
753   Y   48
798   Y   3
798   Y   36
799   Y   1
799   Y   12
807   Y   3
807   Y   36
808   Y   2
808   Y   24
809   Y   1
809   Y   12
830   Y   3
830   Y   36
899   Y   3
899   Y   36
904   Y   3
904   Y   36
912   Y   3
912   Y   36
917   Y   2
917   Y   24
982   Y   4
982   Y   48
987   Y   3
987   Y   36
1011   Y   4
1011   Y   48
1042   Y   4
1042   Y   48
1048   Y   3
1048   Y   36
1121   Y   4
1121   Y   48
1152   Y   4
1152   Y   48
1153   Y   2
1153   Y   24
1179   Y   5
1179   Y   60
1219   Y   5
1219   Y   60
1246   Y   3
1246   Y   36
1292   Y   5
1292   Y   60
1296   Y   4
1296   Y   48
1314   Y   5
1314   Y   60
1343   Y   4
1343   Y   48
1360   Y   5
1360   Y   60
1361   Y   2
1361   Y   24
1367   Y   3
1367   Y   36
1375   Y   2
1375   Y   24
1380   Y   5
1380   Y   60
1392   Y   4
1392   Y   48
1393   Y   2
1393   Y   24
1406   Y   3
1406   Y   36
1419   Y   5
1419   Y   60
1420   Y   3
1420   Y   36
1421   Y   2
1421   Y   24
1430   Y   2
1430   Y   24
1485   Y   4
1485   Y   48
1519   Y   3
1519   Y   36
1533   Y   3
1533   Y   36
1543   Y   5
1543   Y   60
1546   Y   4
1546   Y   48
1567   Y   2
1567   Y   24
1574   Y   4
1574   Y   48
1583   Y   4
1583   Y   48
1683   Y   2
1683   Y   24
1696   Y   3
1696   Y   36
1760   Y   3
1760   Y   36
1805   Y   3
1805   Y   36
1821   Y   2
1821   Y   24
1840   Y   4
1840   Y   48
1841   Y   2
1841   Y   24
1846   Y   4
1846   Y   48
1856   Y   3
1856   Y   36
1868   Y   4
1868   Y   48
1870   Y   1
1870   Y   12
1876   Y   4
1876   Y   48
1877   Y   3
1877   Y   36
1918   Y   5
1918   Y   60
1925   Y   4
1925   Y   48
1937   Y   5
1937   Y   60
1948   Y   5
1948   Y   60
1949   Y   3
1949   Y   36
1958   Y   4
1958   Y   48
1959   Y   2
1959   Y   24
1962   Y   3
1962   Y   36
1979   Y   4
1979   Y   48
1980   Y   2
1980   Y   24
1998   Y   4
1998   Y   48
2003   Y   4
2003   Y   48
2029   Y   5
2029   Y   60
2035   Y   3
2035   Y   36
2050   Y   3
2050   Y   36
2095   Y   2
2095   Y   24
2175   Y   3
2175   Y   36
2251   Y   3
2251   Y   36
2315   Y   5
2315   Y   60
2316   Y   3
2316   Y   36
2332   Y   4
2332   Y   48
2345   Y   4
2345   Y   48
2346   Y   2
2346   Y   24
2381   Y   2
2381   Y   24
2387   Y   4
2387   Y   48
2451   Y   3
2451   Y   36
2459   Y   3
2459   Y   36
2471   Y   4
2471   Y   48
2475   Y   4
2475   Y   48
2476   Y   2
2476   Y   24
2515   Y   4
2515   Y   48
2521   Y   4
2521   Y   48
2536   Y   4
2536   Y   48
2574   Y   2
2574   Y   24
2582   Y   5
2582   Y   60
2583   Y   3
2583   Y   36
2624   Y   2
2624   Y   24
2642   Y   5
2642   Y   60
2643   Y   2
2643   Y   24
2647   Y   2
2647   Y   24
2650   Y   2
2650   Y   24
2656   Y   2
2656   Y   24
2660   Y   2
2660   Y   24
2719   Y   2
2719   Y   24
2740   Y   4
2740   Y   48
2761   Y   5
2761   Y   60
2766   Y   3
2766   Y   36
2771   Y   3
2771   Y   36
2802   Y   4
2802   Y   48
2817   Y   2
2817   Y   24
2834   Y   4
2834   Y   48
2855   Y   4
2855   Y   48
2856   Y   2
2856   Y   24
2870   Y   2
2870   Y   24
2879   Y   4
2879   Y   48
2915   Y   3
2915   Y   36
2922   Y   4
2922   Y   48
2931   Y   4
2931   Y   48
2935   Y   2
2935   Y   24
2948   Y   3
2948   Y   36
2949   Y   2
2949   Y   24
2996   Y   4
2996   Y   48
3011   Y   3
3011   Y   36
3112   Y   3
3112   Y   36
3128   Y   4
3128   Y   48
3129   Y   4
3129   Y   48
3135   Y   4
3135   Y   48
3145   Y   3
3145   Y   36
3171   Y   3
3171   Y   36
3179   Y   3
3179   Y   36
3180   Y   1
3180   Y   12
3185   Y   2
3185   Y   24
3199   Y   5
3199   Y   60
3207   Y   3
3207   Y   36
3212   Y   5
3212   Y   60
3218   Y   5
3218   Y   60
3222   Y   2
3222   Y   24
3249   Y   4
3249   Y   48
3275   Y   3
3275   Y   36
3276   Y   1
3276   Y   12
3279   Y   5
3279   Y   60
3280   Y   3
3280   Y   36
3291   Y   3
3291   Y   36
3312   Y   4
3312   Y   48
3363   Y   5
3363   Y   60
3364   Y   3
3364   Y   36
3367   Y   4
3367   Y   48
3368   Y   2
3368   Y   24
3380   Y   4
3380   Y   48
3403   Y   3
3403   Y   36
3408   Y   3
3408   Y   36
3417   Y   3
3417   Y   36
3422   Y   4
3422   Y   48
3427   Y   4
3427   Y   48
3428   Y   1
3428   Y   12
3436   Y   2
3436   Y   24
3443   Y   4
3443   Y   48
3456   Y   3
3456   Y   36
3457   Y   1
3457   Y   12
3460   Y   2
3460   Y   24
3461   Y   1
3461   Y   12
3465   Y   3
3465   Y   36
3483   Y   3
3483   Y   36
3484   Y   2
3484   Y   24
3494   Y   2
3494   Y   24
3495   Y   2
3495   Y   24
3524   Y   4
3524   Y   48
3529   Y   3
3529   Y   36
3551   Y   2
3551   Y   24
3577   Y   1
3577   Y   12
3587   Y   4
3587   Y   48
3596   Y   4
3596   Y   48
3599   Y   1
3599   Y   12
3608   Y   4
3608   Y   48
3611   Y   3
3611   Y   36
3628   Y   2
3628   Y   24
3633   Y   4
3633   Y   48
3649   Y   4
3649   Y   48
3650   Y   2
3650   Y   24
3655   Y   2
3655   Y   24
3656   Y   1
3656   Y   12
3674   Y   2
3674   Y   24
3710   Y   3
3710   Y   36
3713   Y   3
3713   Y   36
3718   Y   4
3718   Y   48
3727   Y   2
3727   Y   24
3736   Y   3
3736   Y   36
3737   Y   2
3737   Y   24
3741   Y   4
3741   Y   48
3745   Y   3
3745   Y   36
3765   Y   2
3765   Y   24
3788   Y   3
3788   Y   36
3799   Y   3
3799   Y   36
3800   Y   2
3800   Y   24
3831   Y   5
3831   Y   60
3852   Y   3
3852   Y   36
3870   Y   2
3870   Y   24
3935   Y   3
3935   Y   36
3943   Y   4
3943   Y   48
3944   Y   2
3944   Y   24
3965   Y   2
3965   Y   24
3995   Y   5
3995   Y   60
3996   Y   4
3996   Y   48
4007   Y   5
4007   Y   60
4014   Y   4
4014   Y   48
4021   Y   5
4021   Y   60
4025   Y   2
4025   Y   24
4036   Y   4
4036   Y   48
4048   Y   3
4048   Y   36
4060   Y   4
4060   Y   48
4077   Y   3
4077   Y   36
4082   Y   3
4082   Y   36
4092   Y   5
4092   Y   60
4093   Y   4
4093   Y   48
4097   Y   3
4097   Y   36
4111   Y   4
4111   Y   48
4126   Y   4
4126   Y   48
4134   Y   2
4134   Y   24
4147   Y   3
4147   Y   36
4159   Y   3
4159   Y   36
4168   Y   2
4168   Y   24
4175   Y   2
4175   Y   24
4183   Y   2
4183   Y   24
4187   Y   2
4187   Y   24
4190   Y   4
4190   Y   48
4191   Y   2
4191   Y   24
4201   Y   3
4201   Y   36
4205   Y   2
4205   Y   24
4222   Y   2
4222   Y   24
4297   Y   2
4297   Y   24
4298   Y   1
4298   Y   12
4303   Y   3
4303   Y   36
4309   Y   4
4309   Y   48
4310   Y   2
4310   Y   24
4318   Y   1
4318   Y   12
4346   Y   3
4346   Y   36
4356   Y   4
4356   Y   48
4359   Y   1
4359   Y   12
4382   Y   2
4382   Y   24
4393   Y   3
4393   Y   36
4418   Y   4
4418   Y   48
4427   Y   2
4427   Y   24
4434   Y   4
4434   Y   48
4469   Y   2
4469   Y   24
4488   Y   4
4488   Y   48
4502   Y   4
4502   Y   48
4503   Y   2
4503   Y   24
4506   Y   3
4506   Y   36
4518   Y   3
4518   Y   36
4525   Y   2
4525   Y   24
4527   Y   4
4527   Y   48
4537   Y   1
4537   Y   12
4553   Y   2
4553   Y   24
4561   Y   4
4561   Y   48
4567   Y   4
4567   Y   48
4568   Y   2
4568   Y   24
4582   Y   2
4582   Y   24
4594   Y   2
4594   Y   24
4597   Y   3
4597   Y   36
4598   Y   2
4598   Y   24
4606   Y   2
4606   Y   24
4609   Y   3
4609   Y   36
4635   Y   2
4635   Y   24
4642   Y   3
4642   Y   36
4658   Y   2
4658   Y   24
4661   Y   3
4661   Y   36
4662   Y   2
4662   Y   24
4667   Y   2
4667   Y   24
4670   Y   3
4670   Y   36
4675   Y   3
4675   Y   36
4683   Y   3
4683   Y   36
4696   Y   2
4696   Y   24
4699   Y   3
4699   Y   36
4705   Y   3
4705   Y   36
4716   Y   3
4716   Y   36
4733   Y   3
4733   Y   36
4739   Y   3
4739   Y   36
4752   Y   3
4752   Y   36
4759   Y   4
4759   Y   48
4760   Y   3
4760   Y   36
4776   Y   3
4776   Y   36
4798   Y   2
4798   Y   24
4806   Y   4
4806   Y   48
4807   Y   2
4807   Y   24
4811   Y   3
4811   Y   36
4817   Y   3
4817   Y   36
4830   Y   4
4830   Y   48
4836   Y   3
4836   Y   36
4841   Y   2
4841   Y   24
4858   Y   3
4858   Y   36
4868   Y   4
4868   Y   48
4886   Y   5
4886   Y   60
4887   Y   3
4887   Y   36
4896   Y   4
4896   Y   48
4899   Y   2
4899   Y   24
4908   Y   3
4908   Y   36
4941   Y   2
4941   Y   24
4949   Y   2
4949   Y   24
4956   Y   5
4956   Y   60
4957   Y   3
4957   Y   36
4977   Y   3
4977   Y   36
4986   Y   5
4986   Y   60
4987   Y   2
4987   Y   24
4999   Y   3
4999   Y   36
5010   Y   2
5010   Y   24
5029   Y   3
5029   Y   36
5037   Y   4
5037   Y   48
5043   Y   2
5043   Y   24
5060   Y   3
5060   Y   36
5065   Y   4
5065   Y   48
5086   Y   4
5086   Y   48
5104   Y   3
5104   Y   36
5107   Y   5
5107   Y   60
5108   Y   2
5108   Y   24
5113   Y   4
5113   Y   48
5118   Y   4
5118   Y   48
5126   Y   5
5126   Y   60
5130   Y   3
5130   Y   36
5131   Y   2
5131   Y   24
5136   Y   1
5136   Y   12
5144   Y   4
5144   Y   48
5146   Y   3
5146   Y   36
5153   Y   2
5153   Y   24
5166   Y   2
5166   Y   24
5172   Y   3

5172   Y   36
5179   Y   2
5179   Y   24
5194   Y   2
5194   Y   24
5203   Y   5
5203   Y   60
5204   Y   2
5204   Y   24
5208   Y   3
5208   Y   36
5209   Y   2
5209   Y   24
5215   Y   2
5215   Y   24
5222   Y   1
5222   Y   12
5285   Y   3
5285   Y   36
5288   Y   3
5288   Y   36
5326   Y   3
5326   Y   36
5336   Y   3
5336   Y   36
5341   Y   3
5341   Y   36
5344   Y   2
5344   Y   24
5351   Y   2
5351   Y   24
5355   Y   3
5355   Y   36
5359   Y   4
5359   Y   48
5360   Y   2
5360   Y   24
5373   Y   4
5373   Y   48
5386   Y   4
5386   Y   48
5409   Y   3
5409   Y   36
5420   Y   3
5420   Y   36
5424   Y   3
5424   Y   36
5439   Y   3
5439   Y   36
5444   Y   3
5444   Y   36
5448   Y   2
5448   Y   24
5464   Y   2
5464   Y   24
5468   Y   3
5468   Y   36
5472   Y   2
5472   Y   24
5480   Y   4
5480   Y   48
5481   Y   2
5481   Y   24
5490   Y   4
5490   Y   48
5500   Y   3
5500   Y   36
5516   Y   3
5516   Y   36
5521   Y   4
5521   Y   48
5533   Y   3
5533   Y   36
5536   Y   4
5536   Y   48
5537   Y   2
5537   Y   24
5556   Y   4
5556   Y   48
5560   Y   4
5560   Y   48
5563   Y   4
5563   Y   48
5566   Y   3
5566   Y   36
5573   Y   3
5573   Y   36
5589   Y   2
5589   Y   24
5592   Y   3
5592   Y   36
5630   Y   3
5630   Y   36
5631   Y   2
5631   Y   24
5636   Y   2
5636   Y   24
5652   Y   4
5652   Y   48
5653   Y   2
5653   Y   24
5676   Y   1
5676   Y   12
5686   Y   2
5686   Y   24
5700   Y   3
5700   Y   36
5701   Y   1
5701   Y   12
5717   Y   3
5717   Y   36
5722   Y   2
5722   Y   24
5759   Y   3
5759   Y   36
5770   Y   2
5770   Y   24
5775   Y   5
5775   Y   60
5787   Y   3
5787   Y   36
5797   Y   5
5797   Y   60
5806   Y   1
5806   Y   12
5855   Y   2
5855   Y   24
5878   Y   3
5878   Y   36
5896   Y   4
5896   Y   48
5932   Y   2
5932   Y   24
5939   Y   2
5939   Y   24
5944   Y   3
5944   Y   36
5952   Y   4
5952   Y   48
5986   Y   3
5986   Y   36
5987   Y   1
5987   Y   12
5998   Y   4
5998   Y   48
6016   Y   5
6016   Y   60
6017   Y   2
6017   Y   24
6023   Y   2
6023   Y   24
6031   Y   4
6031   Y   48
6061   Y   2
6061   Y   24
6080   Y   2
6080   Y   24
6104   Y   3
6104   Y   36
6115   Y   3
6115   Y   36
6121   Y   2
6121   Y   24
6122   Y   1
6122   Y   12
6128   Y   4
6128   Y   48
6140   Y   4
6140   Y   48
6141   Y   1
6141   Y   12
6152   Y   3
6152   Y   36
6153   Y   1
6153   Y   12
6163   Y   4
6163   Y   48
6164   Y   2
6164   Y   24
6167   Y   1
6167   Y   12
6187   Y   1
6187   Y   12
6196   Y   3
6196   Y   36
6205   Y   4
6205   Y   48
6257   Y   4
6257   Y   48
6258   Y   2
6258   Y   24
6274   Y   2
6274   Y   24
6278   Y   5
6278   Y   60
6279   Y   2
6279   Y   24
6326   Y   2
6326   Y   24
6337   Y   3
6337   Y   36
6352   Y   1
6352   Y   12
6354   Y   3
6354   Y   36
6355   Y   2
6355   Y   24
6377   Y   2
6377   Y   24
6387   Y   2
6387   Y   24
6392   Y   4
6392   Y   48
6399   Y   2
6399   Y   24
6405   Y   3
6405   Y   36
6406   Y   2
6406   Y   24
6418   Y   2
6418   Y   24
6422   Y   3
6422   Y   36
6430   Y   3
6430   Y   36
6431   Y   2
6431   Y   24
6434   Y   3
6434   Y   36
6450   Y   3
6450   Y   36
6455   Y   4
6455   Y   48
6456   Y   1
6456   Y   12
6469   Y   3
6469   Y   36
6470   Y   1
6470   Y   12
6511   Y   4
6511   Y   48
6512   Y   2
6512   Y   24
6524   Y   2
6524   Y   24
6574   Y   3
6574   Y   36
6577   Y   2
6577   Y   24
6583   Y   4
6583   Y   48
6584   Y   2
6584   Y   24
6601   Y   1
6601   Y   12
6625   Y   4
6625   Y   48
6626   Y   2
6626   Y   24
6633   Y   4
6633   Y   48
6634   Y   1
6634   Y   12
6645   Y   2
6645   Y   24
6672   Y   5
6672   Y   60
6683   Y   4
6683   Y   48
6687   Y   3
6687   Y   36
6693   Y   4
6693   Y   48
6703   Y   3
6703   Y   36
6704   Y   1
6704   Y   12
6711   Y   3
6711   Y   36
6740   Y   3
6740   Y   36
6741   Y   1
6741   Y   12
6750   Y   1
6750   Y   12
6757   Y   2
6757   Y   24
6781   Y   3
6781   Y   36
6793   Y   2
6793   Y   24
6799   Y   2
6799   Y   24
6803   Y   2
6803   Y   24
6811   Y   2
6811   Y   24
6818   Y   3
6818   Y   36
6819   Y   3
6819   Y   36
6887   Y   3
6887   Y   36
6888   Y   3
6888   Y   36
6929   Y   3
6929   Y   36
6947   Y   3
6947   Y   36
6970   Y   4
6970   Y   48
6988   Y   3
6988   Y   36
7005   Y   4
7005   Y   48
7035   Y   3
7035   Y   36
7044   Y   4
7044   Y   48
7052   Y   4
7052   Y   48
7053   Y   2
7053   Y   24
7069   Y   4
7069   Y   48
7070   Y   3
7070   Y   36
7075   Y   4
7075   Y   48
7081   Y   4
7081   Y   48
7098   Y   2
7098   Y   24
7104   Y   2
7104   Y   24
7109   Y   4
7109   Y   48
7113   Y   4
7113   Y   48
7224   Y   1
7224   Y   12
7227   Y   1
7227   Y   12
7228   Y   1
7228   Y   12
7245   Y   3
7245   Y   36
7246   Y   3
7246   Y   36
7333   Y   4
7333   Y   48
7341   Y   3
7341   Y   36
7347   Y   3
7347   Y   36
7381   Y   4
7381   Y   48
7386   Y   4
7386   Y   48
7411   Y   4
7411   Y   48
7421   Y   4
7421   Y   48
7437   Y   3
7437   Y   36
7443   Y   3
7443   Y   36
7463   Y   3
7463   Y   36
7477   Y   3
7477   Y   36
7507   Y   4
7507   Y   48
7508   Y   2
7508   Y   24
7511   Y   3
7511   Y   36
7546   Y   4
7546   Y   48
7569   Y   3
7569   Y   36
7576   Y   4
7576   Y   48
7577   Y   1
7577   Y   12
7683   Y   2
7683   Y   24
7689   Y   3
7689   Y   36
7758   Y   3
7758   Y   36
7814   Y   3
7814   Y   36
7887   Y   1
7887   Y   12
7945   Y   1
7945   Y   12
7962   Y   1
7962   Y   12
7963   Y   1
7963   Y   12
7978   Y   1
7978   Y   12
7981   Y   1
7981   Y   12
8004   Y   1
8004   Y   12
8016   Y   1
8016   Y   12
8030   Y   2
8030   Y   24
8038   Y   2
8038   Y   24
8040   Y   2
8040   Y   24
8064   Y   2
8064   Y   24
8066   Y   2
8066   Y   24
8143   Y   3
8143   Y   36
8148   Y   2
8148   Y   24
8167   Y   3
8167   Y   36
8169   Y   3
8169   Y   36
8192   Y   2
8192   Y   24
8200   Y   4
8200   Y   48
8201   Y   3
8201   Y   36
8211   Y   4
8211   Y   48
8212   Y   3
8212   Y   36
8225   Y   3
8225   Y   36
8226   Y   2
8226   Y   24
8279   Y   4
8279   Y   48
8291   Y   4
8291   Y   48
8302   Y   4
8302   Y   48
8314   Y   4
8314   Y   48
8343   Y   3
8343   Y   36
8378   Y   2
8378   Y   24
8395   Y   3
8395   Y   36
8407   Y   3
8407   Y   36
8408   Y   2
8408   Y   24
8417   Y   3
8417   Y   36
8477   Y   4
8477   Y   48
8502   Y   3
8502   Y   36
8503   Y   2
8503   Y   24
8562   Y   3
8562   Y   36
8594   Y   4
8594   Y   48
8599   Y   3
8599   Y   36
8619   Y   3
8619   Y   36
8660   Y   3
8660   Y   36
8666   Y   4
8666   Y   48
8673   Y   4
8673   Y   48
8691   Y   2
8691   Y   24
8694   Y   4
8694   Y   48
8695   Y   3
8695   Y   36
8707   Y   2
8707   Y   24
8713   Y   5
8713   Y   60
8726   Y   4
8726   Y   48
8776   Y   5
8776   Y   60
8792   Y   4
8792   Y   48
8820   Y   4
8820   Y   48
8821   Y   2
8821   Y   24
8829   Y   3
8829   Y   36
8836   Y   3
8836   Y   36
8842   Y   3
8842   Y   36
8854   Y   5
8854   Y   60
8863   Y   4
8863   Y   48
8864   Y   2
8864   Y   24
8902   Y   4
8902   Y   48
8910   Y   1
8910   Y   12
8923   Y   3
8923   Y   36
8924   Y   2
8924   Y   24
9014   Y   4
9014   Y   48
9021   Y   3
9021   Y   36
9039   Y   3
9039   Y   36
9089   Y   4
9089   Y   48
9090   Y   1
9090   Y   12
9105   Y   5
9105   Y   60
9115   Y   3
9115   Y   36
9160   Y   4
9160   Y   48
9165   Y   3
9165   Y   36
9168   Y   3
9168   Y   36
9224   Y   5
9224   Y   60
9239   Y   3
9239   Y   36
9246   Y   1
9246   Y   12
9255   Y   1
9255   Y   12
9266   Y   2
9266   Y   24
9280   Y   4
9280   Y   48
9293   Y   2
9293   Y   24
9299   Y   1
9299   Y   12
9323   Y   2
9323   Y   24
9416   Y   5
9416   Y   60
9434   Y   4
9434   Y   48
9438   Y   3
9438   Y   36
9454   Y   3
9454   Y   36
9456   Y   1
9456   Y   12
9478   Y   5
9478   Y   60
9479   Y   1
9479   Y   12
9512   Y   3
9512   Y   36
9520   Y   5
9520   Y   60
9534   Y   4
9534   Y   48
9569   Y   2
9569   Y   24
9584   Y   3
9584   Y   36
9599   Y   4
9599   Y   48
9600   Y   2
9600   Y   24
9626   Y   5
9626   Y   60
9629   Y   3
9629   Y   36
9674   Y   4
9674   Y   48
9701   Y   2
9701   Y   24
9721   Y   4
9721   Y   48
9722   Y   2
9722   Y   24
9795   Y   4
9795   Y   48
9796   Y   2
9796   Y   24
9848   Y   3
9848   Y   36
9877   Y   4
9877   Y   48
9888   Y   3
9888   Y   36
9904   Y   3
9904   Y   36
9981   Y   3
9981   Y   36
10009   Y   3
10009   Y   36
10012   Y   4
10012   Y   48
10013   Y   3
10013   Y   36
10052   Y   4
10052   Y   48
10114   Y   3
10114   Y   36
10121   Y   5
10121   Y   60
10129   Y   3
10129   Y   36
10156   Y   3
10156   Y   36
10178   Y   2
10178   Y   24
10227   Y   3
10227   Y   36
10233   Y   5
10233   Y   60
10234   Y   4
10234   Y   48
10235   Y   3
10235   Y   36
10244   Y   4
10244   Y   48
10316   Y   3
10316   Y   36
10362   Y   3
10362   Y   36
10366   Y   3
10366   Y   36
10432   Y   3
10432   Y   36
10433   Y   3
10433   Y   36
10457   Y   5
10457   Y   60
10458   Y   3
10458   Y   36
10479   Y   2
10479   Y   24
10523   Y   1
10523   Y   12
10581   Y   2
10581   Y   24
10602   Y   4
10602   Y   48
10606   Y   3
10606   Y   36
10649   Y   4
10649   Y   48
10655   Y   5
10655   Y   60
10688   Y   3

10688   Y   36
10692   Y   4
10692   Y   48
10697   Y   3
10697   Y   36
10753   Y   4
10753   Y   48
10767   Y   4
10767   Y   48
10770   Y   4
10770   Y   48
10815   Y   3
10815   Y   36
10831   Y   4
10831   Y   48
10840   Y   3
10840   Y   36
10845   Y   4
10845   Y   48
10859   Y   3
10859   Y   36
10900   Y   5
10900   Y   60
10930   Y   3
10930   Y   36
10966   Y   3
10966   Y   36
10973   Y   3
10973   Y   36
10989   Y   3
10989   Y   36
10994   Y   3
10994   Y   36
11033   Y   5
11033   Y   60
11056   Y   5
11056   Y   60
11096   Y   3
11096   Y   36
11100   Y   4
11100   Y   48
11114   Y   4
11114   Y   48
11224   Y   3
11224   Y   36
11292   Y   2
11292   Y   24
11400   Y   5
11400   Y   60
11401   Y   2
11401   Y   24
11413   Y   3
11413   Y   36
11449   Y   2
11449   Y   24
11532   Y   2
11532   Y   24
11559   Y   2
11559   Y   24
11571   Y   4
11571   Y   48
11621   Y   4
11621   Y   48
11625   Y   4
11625   Y   48
11646   Y   5
11646   Y   60
11667   Y   4
11667   Y   48
11668   Y   3
11668   Y   36
11680   Y   3
11680   Y   36
11690   Y   4
11690   Y   48
11695   Y   3
11695   Y   36
11699   Y   5
11699   Y   60
11701   Y   3
11701   Y   36
11706   Y   4
11706   Y   48
11725   Y   4
11725   Y   48
11726   Y   3
11726   Y   36
11739   Y   4
11739   Y   48
11755   Y   4
11755   Y   48
11765   Y   3
11765   Y   36
11772   Y   4
11772   Y   48
11773   Y   3
11773   Y   36
11779   Y   4
11779   Y   48
11787   Y   4
11787   Y   48
11795   Y   4
11795   Y   48
11806   Y   5
11806   Y   60
11819   Y   3
11819   Y   36
11852   Y   3
11852   Y   36
11855   Y   3
11855   Y   36
11882   Y   2
11882   Y   24
11892   Y   4
11892   Y   48
11893   Y   3
11893   Y   36
11913   Y   3
11913   Y   36
11935   Y   4
11935   Y   48
11948   Y   3
11948   Y   36
11963   Y   4
11963   Y   48
11978   Y   4
11978   Y   48
11979   Y   3
11979   Y   36
11990   Y   3
11990   Y   36
12001   Y   3
12001   Y   36
12002   Y   2
12002   Y   24
12013   Y   4
12013   Y   48
12045   Y   3
12045   Y   36
12080   Y   2
12080   Y   24
12085   Y   3
12085   Y   36
12086   Y   2
12086   Y   24
12091   Y   2
12091   Y   24
12191   Y   3
12191   Y   36
12228   Y   4
12228   Y   48
12234   Y   2
12234   Y   24
12260   Y   3
12260   Y   36
12275   Y   4
12275   Y   48
12284   Y   4
12284   Y   48
12320   Y   2
12320   Y   24
12329   Y   4
12329   Y   48
12341   Y   3
12341   Y   36
12376   Y   4
12376   Y   48
12382   Y   3
12382   Y   36
12385   Y   1
12385   Y   12
12438   Y   5
12438   Y   60
12443   Y   3
12443   Y   36
12447   Y   3
12447   Y   36
12506   Y   3
12506   Y   36
12510   Y   4
12510   Y   48
12516   Y   3
12516   Y   36
12526   Y   4
12526   Y   48
12561   Y   4
12561   Y   48
12596   Y   3
12596   Y   36
12615   Y   5
12615   Y   60
12632   Y   4
12632   Y   48
12708   Y   3
12708   Y   36
12712   Y   5
12712   Y   60
12713   Y   4
12713   Y   48
12724   Y   3
12724   Y   36
12725   Y   3
12725   Y   36
12751   Y   4
12751   Y   48
12755   Y   5
12755   Y   60
12756   Y   3
12756   Y   36
12817   Y   4
12817   Y   48
12897   Y   4
12897   Y   48
12919   Y   2
12919   Y   24
12939   Y   3
12939   Y   36
12942   Y   5
12942   Y   60
12945   Y   5
12945   Y   60
12964   Y   4
12964   Y   48
13009   Y   3
13009   Y   36
13025   Y   5
13025   Y   60
13027   Y   2
13027   Y   24
13071   Y   4
13071   Y   48
13077   Y   4
13077   Y   48
13088   Y   4
13088   Y   48
13142   Y   2
13142   Y   24
13185   Y   3
13185   Y   36
13233   Y   4
13233   Y   48
13234   Y   3
13234   Y   36
13283   Y   3
13283   Y   36
13286   Y   3
13286   Y   36
13341   Y   3
13341   Y   36
13347   Y   3
13347   Y   36
13365   Y   4
13365   Y   48
13378   Y   4
13378   Y   48
13401   Y   2
13401   Y   24
13412   Y   4
13412   Y   48
13468   Y   4
13468   Y   48
13563   Y   3
13563   Y   36
13566   Y   3
13566   Y   36
13580   Y   3
13580   Y   36
13581   Y   3
13581   Y   36
13614   Y   4
13614   Y   48
13618   Y   3
13618   Y   36
13624   Y   2
13624   Y   24
13656   Y   4
13656   Y   48
13695   Y   4
13695   Y   48
13699   Y   4
13699   Y   48
13712   Y   3
13712   Y   36
13721   Y   3
13721   Y   36
13730   Y   2
13730   Y   24
13795   Y   4
13795   Y   48
13807   Y   2
13807   Y   24
13820   Y   3
13820   Y   36
13899   Y   2
13899   Y   24
13923   Y   5
13923   Y   60
13949   Y   3
13949   Y   36
13953   Y   3
13953   Y   36
14013   Y   4
14013   Y   48
14014   Y   2
14014   Y   24
14028   Y   4
14028   Y   48
14055   Y   2
14055   Y   24
14074   Y   3
14074   Y   36
14075   Y   3
14075   Y   36
14132   Y   3
14132   Y   36
14144   Y   4
14144   Y   48
14152   Y   4
14152   Y   48
14163   Y   4
14163   Y   48
14164   Y   2
14164   Y   24
14185   Y   3
14185   Y   36
14190   Y   2
14190   Y   24
14210   Y   4
14210   Y   48
14211   Y   2
14211   Y   24
14216   Y   2
14216   Y   24
14218   Y   3
14218   Y   36
14222   Y   5
14222   Y   60
14228   Y   2
14228   Y   24
14233   Y   4
14233   Y   48
14258   Y   4
14258   Y   48
14267   Y   4
14267   Y   48
14309   Y   2
14309   Y   24
14318   Y   3
14318   Y   36
14384   Y   1
14384   Y   12
14401   Y   1
14401   Y   12
14427   Y   1
14427   Y   12
14437   Y   1
14437   Y   12
14533   Y   4
14533   Y   48
14546   Y   3
14546   Y   36
14554   Y   4
14554   Y   48
14555   Y   1
14555   Y   12
14560   Y   2
14560   Y   24
14607   Y   4
14607   Y   48
14657   Y   5
14657   Y   60
14667   Y   4
14667   Y   48
14687   Y   4
14687   Y   48
14694   Y   5
14694   Y   60
14712   Y   5
14712   Y   60
14740   Y   3
14740   Y   36
14771   Y   2
14771   Y   24
14818   Y   5
14818   Y   60
14914   Y   2
14914   Y   24
14942   Y   3
14942   Y   36
15065   Y   4
15065   Y   48
15072   Y   2
15072   Y   24
15075   Y   3
15075   Y   36
15076   Y   3
15076   Y   36
15154   Y   4
15154   Y   48
15155   Y   2
15155   Y   24
15187   Y   3
15187   Y   36
15236   Y   3
15236   Y   36
15242   Y   3
15242   Y   36
15249   Y   4
15249   Y   48
15251   Y   2
15251   Y   24
15255   Y   2
15255   Y   24
15269   Y   3
15269   Y   36
15294   Y   3
15294   Y   36
15329   Y   4
15329   Y   48
15344   Y   4
15344   Y   48
15400   Y   3
15400   Y   36
15470   Y   4
15470   Y   48
15471   Y   3
15471   Y   36
15478   Y   3
15478   Y   36
15491   Y   4
15491   Y   48
15492   Y   1
15492   Y   12
15511   Y   4
15511   Y   48
15512   Y   1
15512   Y   12
15518   Y   3
15518   Y   36
15526   Y   4
15526   Y   48
15540   Y   3
15540   Y   36
15557   Y   4
15557   Y   48
15585   Y   3
15585   Y   36
15601   Y   2
15601   Y   24
15602   Y   1
15602   Y   12
15612   Y   2
15612   Y   24
15646   Y   4
15646   Y   48
15661   Y   3
15661   Y   36
15683   Y   3
15683   Y   36
15703   Y   4
15703   Y   48
15704   Y   1
15704   Y   12
15705   Y   1
15705   Y   12
15731   Y   4
15731   Y   48
15732   Y   2
15732   Y   24
15746   Y   3
15746   Y   36
15856   Y   3
15856   Y   36
15861   Y   1
15861   Y   12
15898   Y   4
15898   Y   48
15902   Y   4
15902   Y   48
15943   Y   2
15943   Y   24
15967   Y   2
15967   Y   24
15976   Y   1
15976   Y   12
16016   Y   3
16016   Y   36
16018   Y   3
16018   Y   36
16048   Y   3
16048   Y   36
16059   Y   3
16059   Y   36
16087   Y   1
16087   Y   12
16117   Y   4
16117   Y   48
16118   Y   3
16118   Y   36
16146   Y   3
16146   Y   36
16153   Y   2
16153   Y   24
16160   Y   2
16160   Y   24
16173   Y   4
16173   Y   48
16174   Y   2
16174   Y   24
16178   Y   3
16178   Y   36
16193   Y   4
16193   Y   48
16216   Y   4
16216   Y   48
16222   Y   1
16222   Y   12
16231   Y   4
16231   Y   48
16245   Y   3
16245   Y   36
16286   Y   3
16286   Y   36
16298   Y   3
16298   Y   36
16309   Y   5
16309   Y   60
16329   Y   4
16329   Y   48
16343   Y   3
16343   Y   36
16356   Y   4
16356   Y   48
16468   Y   3
16468   Y   36
16499   Y   1
16499   Y   12
16566   Y   2
16566   Y   24
16567   Y   2
16567   Y   24
16574   Y   1
16574   Y   12
16608   Y   3
16608   Y   36
16626   Y   3
16626   Y   36
16645   Y   3
16645   Y   36
16664   Y   3
16664   Y   36
16668   Y   3
16668   Y   36
16676   Y   4
16676   Y   48
16715   Y   3
16715   Y   36
16720   Y   4
16720   Y   48
16738   Y   3
16738   Y   36
16742   Y   3
16742   Y   36
16743   Y   2
16743   Y   24
16752   Y   4
16752   Y   48
16753   Y   4
16753   Y   48
16756   Y   2
16756   Y   24
16759   Y   5
16759   Y   60
16760   Y   1
16760   Y   12
16776   Y   1
16776   Y   12
16779   Y   3
16779   Y   36
16791   Y   3
16791   Y   36
16792   Y   2
16792   Y   24
16804   Y   2
16804   Y   24
16840   Y   3
16840   Y   36
16865   Y   4
16865   Y   48
16892   Y   4
16892   Y   48
16906   Y   4
16906   Y   48
16942   Y   2
16942   Y   24
16943   Y   4
16943   Y   48
16959   Y   2
16959   Y   24
16962   Y   4
16962   Y   48

16967   Y   5
16967   Y   60
16997   Y   3
16997   Y   36
16998   Y   4
16998   Y   48
17007   Y   3
17007   Y   36
17008   Y   3
17008   Y   36
17015   Y   2
17015   Y   24
17019   Y   3
17019   Y   36
17043   Y   4
17043   Y   48
17056   Y   1
17056   Y   12
17103   Y   3
17103   Y   36
17108   Y   3
17108   Y   36
17109   Y   2
17109   Y   24
17124   Y   4
17124   Y   48
17125   Y   3
17125   Y   36
17126   Y   2
17126   Y   24
17148   Y   3
17148   Y   36
17171   Y   1
17171   Y   12
17207   Y   3
17207   Y   36
17211   Y   3
17211   Y   36
17214   Y   4
17214   Y   48
17225   Y   3
17225   Y   36
17229   Y   4
17229   Y   48
17230   Y   3
17230   Y   36
17252   Y   3
17252   Y   36
17258   Y   3
17258   Y   36
17293   Y   3
17293   Y   36
17326   Y   5
17326   Y   60
17399   Y   4
17399   Y   48
17473   Y   3
17473   Y   36
17476   Y   3
17476   Y   36
17573   Y   4
17573   Y   48
17604   Y   3
17604   Y   36
17617   Y   3
17617   Y   36
17663   Y   4
17663   Y   48
17672   Y   3
17672   Y   36
17725   Y   3
17725   Y   36
17744   Y   3
17744   Y   36
17752   Y   4
17752   Y   48
17784   Y   4
17784   Y   48
17787   Y   4
17787   Y   48
17803   Y   4
17803   Y   48
17898   Y   4
17898   Y   48
17921   Y   4
17921   Y   48
18035   Y   2
18035   Y   24
18074   Y   5
18074   Y   60
18109   Y   3
18109   Y   36
18129   Y   2
18129   Y   24
18157   Y   5
18157   Y   60
18167   Y   4
18167   Y   48
18168   Y   4
18168   Y   48
18220   Y   2
18220   Y   24
18235   Y   4
18235   Y   48
18236   Y   4
18236   Y   48
18261   Y   4
18261   Y   48
18262   Y   2
18262   Y   24
18280   Y   3
18280   Y   36
18306   Y   3
18306   Y   36
18312   Y   1
18312   Y   12
18333   Y   2
18333   Y   24
18361   Y   2
18361   Y   24
18367   Y   3
18367   Y   36
18400   Y   5
18400   Y   60
18403   Y   5
18403   Y   60
18474   Y   4
18474   Y   48
18523   Y   2
18523   Y   24
18533   Y   4
18533   Y   48
18554   Y   4
18554   Y   48
18564   Y   3
18564   Y   36
18565   Y   3
18565   Y   36
18589   Y   4
18589   Y   48
18590   Y   3
18590   Y   36
18604   Y   4
18604   Y   48
18613   Y   3
18613   Y   36
18629   Y   3
18629   Y   36
18635   Y   2
18635   Y   24
18681   Y   2
18681   Y   24
18692   Y   1
18692   Y   12
18736   Y   1
18736   Y   12
18798   Y   3
18798   Y   36
18826   Y   1
18826   Y   12
18840   Y   3
18840   Y   36
18846   Y   3
18846   Y   36
18852   Y   4
18852   Y   48
18890   Y   4
18890   Y   48
18898   Y   3
18898   Y   36
18913   Y   4
18913   Y   48
18922   Y   4
18922   Y   48
18923   Y   3
18923   Y   36
18953   Y   2
18953   Y   24
18968   Y   4
18968   Y   48
18997   Y   5
18997   Y   60
19031   Y   2
19031   Y   24
19036   Y   3
19036   Y   36
19040   Y   4
19040   Y   48
19060   Y   5
19060   Y   60
19082   Y   2
19082   Y   24
19136   Y   4
19136   Y   48
19162   Y   3
19162   Y   36
19172   Y   3
19172   Y   36
19176   Y   3
19176   Y   36
19177   Y   3
19177   Y   36
19199   Y   5
19199   Y   60
19220   Y   2
19220   Y   24
19240   Y   2
19240   Y   24
19251   Y   3
19251   Y   36
19253   Y   2
19253   Y   24
19267   Y   1
19267   Y   12
19279   Y   4
19279   Y   48
19288   Y   4
19288   Y   48
19289   Y   2
19289   Y   24
19323   Y   5
19323   Y   60
19324   Y   3
19324   Y   36
19327   Y   2
19327   Y   24
19335   Y   2
19335   Y   24
19363   Y   3
19363   Y   36
19375   Y   4
19375   Y   48
19381   Y   1
19381   Y   12
19388   Y   2
19388   Y   24
19417   Y   4
19417   Y   48
19418   Y   3
19418   Y   36
19436   Y   3
19436   Y   36
19443   Y   4
19443   Y   48
19444   Y   2
19444   Y   24
19449   Y   3
19449   Y   36
19461   Y   3
19461   Y   36
19497   Y   4
19497   Y   48
19506   Y   4
19506   Y   48
19507   Y   3
19507   Y   36
19531   Y   3
19531   Y   36
19540   Y   2
19540   Y   24
19554   Y   4
19554   Y   48
19577   Y   2
19577   Y   24
19589   Y   2
19589   Y   24
19614   Y   3
19614   Y   36
19672   Y   4
19672   Y   48
19686   Y   2
19686   Y   24
19711   Y   3
19711   Y   36
19723   Y   5
19723   Y   60
19724   Y   5
19724   Y   60
19733   Y   4
19733   Y   48
19769   Y   3
19769   Y   36
19778   Y   3
19778   Y   36
19790   Y   4
19790   Y   48
19857   Y   4
19857   Y   48
19871   Y   4
19871   Y   48
19874   Y   4
19874   Y   48
19875   Y   3
19875   Y   36
19887   Y   4
19887   Y   48
19893   Y   5
19893   Y   60
19987   Y   4
19987   Y   48
19988   Y   2
19988   Y   24
19999   Y   4
19999   Y   48
20003   Y   2
20003   Y   24
20021   Y   2
20021   Y   24
20025   Y   5
20025   Y   60
20026   Y   3
20026   Y   36
20054   Y   4
20054   Y   48
20064   Y   4
20064   Y   48
20065   Y   3
20065   Y   36
20071   Y   4
20071   Y   48
20125   Y   4
20125   Y   48
20133   Y   5
20133   Y   60
20140   Y   1
20140   Y   12
20200   Y   4
20200   Y   48
20226   Y   3
20226   Y   36
20241   Y   5
20241   Y   60
20261   Y   4
20261   Y   48
20262   Y   2
20262   Y   24
20286   Y   3
20286   Y   36
20297   Y   4
20297   Y   48
20298   Y   3
20298   Y   36
20299   Y   3
20299   Y   36
20300   Y   1
20300   Y   12
20313   Y   3
20313   Y   36
20317   Y   3
20317   Y   36
20393   Y   3
20393   Y   36
20402   Y   4
20402   Y   48
20426   Y   4
20426   Y   48
20487   Y   3
20487   Y   36
20535   Y   2
20535   Y   24
20543   Y   4
20543   Y   48
20602   Y   2
20602   Y   24
20614   Y   3
20614   Y   36
20629   Y   3
20629   Y   36
20641   Y   3
20641   Y   36
20688   Y   4
20688   Y   48
20705   Y   4
20705   Y   48
20730   Y   3
20730   Y   36
20787   Y   5
20787   Y   60
20788   Y   2
20788   Y   24
20810   Y   5
20810   Y   60
20823   Y   3
20823   Y   36
20827   Y   2
20827   Y   24
20831   Y   1
20831   Y   12
20943   Y   5
20943   Y   60
20956   Y   4
20956   Y   48
20969   Y   3
20969   Y   36
20979   Y   4
20979   Y   48
20989   Y   4
20989   Y   48
21009   Y   4
21009   Y   48
21013   Y   4
21013   Y   48
21026   Y   2
21026   Y   24
21074   Y   4
21074   Y   48
21075   Y   3
21075   Y   36
21080   Y   4
21080   Y   48
21091   Y   3
21091   Y   36
21092   Y   3
21092   Y   36
21097   Y   4
21097   Y   48
21103   Y   3
21103   Y   36
21104   Y   3
21104   Y   36
21165   Y   2
21165   Y   24
21176   Y   5
21176   Y   60
21180   Y   5
21180   Y   60
21191   Y   3
21191   Y   36
21194   Y   3
21194   Y   36
21210   Y   2
21210   Y   24
21225   Y   4
21225   Y   48
21247   Y   5
21247   Y   60
21265   Y   3
21265   Y   36
21283   Y   5
21283   Y   60
21288   Y   3
21288   Y   36
21296   Y   4
21296   Y   48
21318   Y   4
21318   Y   48
21344   Y   2
21344   Y   24
21347   Y   5
21347   Y   60
21348   Y   3
21348   Y   36
21359   Y   2
21359   Y   24
21375   Y   3
21375   Y   36
21382   Y   4
21382   Y   48
21412   Y   2
21412   Y   24
21425   Y   4
21425   Y   48
21440   Y   3
21440   Y   36
21474   Y   4
21474   Y   48
21475   Y   2
21475   Y   24
21484   Y   4
21484   Y   48
21506   Y   2
21506   Y   24
21534   Y   4
21534   Y   48
21535   Y   2
21535   Y   24
21562   Y   5
21562   Y   60
21571   Y   3
21571   Y   36
21578   Y   4
21578   Y   48
21579   Y   1
21579   Y   12
21585   Y   5
21585   Y   60
21586   Y   4
21586   Y   48
21608   Y   4
21608   Y   48
21609   Y   4
21609   Y   48
21612   Y   2
21612   Y   24
21620   Y   3
21620   Y   36
21627   Y   3
21627   Y   36
21636   Y   2
21636   Y   24
21645   Y   2
21645   Y   24
21668   Y   4
21668   Y   48
21698   Y   4
21698   Y   48
21701   Y   3
21701   Y   36
21707   Y   1
21707   Y   12
21713   Y   1
21713   Y   12
21720   Y   3
21720   Y   36
21734   Y   2
21734   Y   24
21752   Y   3
21752   Y   36
21776   Y   1
21776   Y   12
21805   Y   2
21805   Y   24
21816   Y   4
21816   Y   48
21820   Y   4
21820   Y   48
21823   Y   4
21823   Y   48
21846   Y   3
21846   Y   36
21850   Y   5
21850   Y   60
22009   Y   1
22009   Y   12
22016   Y   2
22016   Y   24
22039   Y   4
22039   Y   48
22105   Y   4
22105   Y   48
22183   Y   4
22183   Y   48
22208   Y   3
22208   Y   36
22209   Y   1
22209   Y   12
22219   Y   4
22219   Y   48
22231   Y   5
22231   Y   60
22296   Y   2
22296   Y   24
22306   Y   4
22306   Y   48
22329   Y   5
22329   Y   60
22345   Y   1
22345   Y   12
22369   Y   2
22369   Y   24
22373   Y   3
22373   Y   36
22397   Y   4
22397   Y   48
22414   Y   3
22414   Y   36
22417   Y   3
22417   Y   36
22459   Y   5
22459   Y   60
22472   Y   5
22472   Y   60
22499   Y   4
22499   Y   48
22512   Y   5
22512   Y   60
22516   Y   3
22516   Y   36
22523   Y   2
22523   Y   24
22567   Y   2
22567   Y   24
22605   Y   4
22605   Y   48
22716   Y   3
22716   Y   36
22735   Y   3
22735   Y   36
22745   Y   5
22745   Y   60
22746   Y   3
22746   Y   36
22755   Y   3
22755   Y   36
22801   Y   3
22801   Y   36
22818   Y   3
22818   Y   36
22869   Y   3
22869   Y   36
22873   Y   5
22873   Y   60
22889   Y   3
22889   Y   36
22962   Y   4
22962   Y   48
23023   Y   2
23023   Y   24
23024   Y   1
23024   Y   12
23046   Y   4
23046   Y   48
23092   Y   2
23092   Y   24
23102   Y   4
23102   Y   48
23129   Y   4
23129   Y   48
23204   Y   3
23204   Y   36
23267   Y   4
23267   Y   48
23352   Y   4
23352   Y   48
23360   Y   3
23360   Y   36
23365   Y   2
23365   Y   24
23375   Y   4
23375   Y   48
23411   Y   4
23411   Y   48
23469   Y   4
23469   Y   48
23589   Y   4
23589   Y   48
23602   Y   4
23602   Y   48
23783   Y   2
23783   Y   24
23930   Y   3
23930   Y   36
23938   Y   2
23938   Y   24
23953   Y   4
23953   Y   48
23957   Y   5
23957   Y   60
23963   Y   3
23963   Y   36
23986   Y   5
23986   Y   60
24027   Y   4
24027   Y   48
24030   Y   4
24030   Y   48
24031   Y   1
24031   Y   12
24060   Y   1
24060   Y   12
24073   Y   2
24073   Y   24
24081   Y   5
24081   Y   60
24111   Y   3
24111   Y   36
24126   Y   5
24126   Y   60
24128   Y   3
24128   Y   36
24163   Y   5
24163   Y   60
24186   Y   4
24186   Y   48
24207   Y   1
24207   Y   12
24214   Y   2
24214   Y   24
24219   Y   4
24219   Y   48
24229   Y   5
24229   Y   60
24234   Y   5

24234   Y   60
24253   Y   2
24253   Y   24
24260   Y   4
24260   Y   48
24276   Y   5
24276   Y   60
24296   Y   5
24296   Y   60
24307   Y   2
24307   Y   24
24319   Y   3
24319   Y   36
24323   Y   1
24323   Y   12
24362   Y   3
24362   Y   36
24363   Y   2
24363   Y   24
24377   Y   4
24377   Y   48
24378   Y   2
24378   Y   24
24414   Y   1
24414   Y   12
24426   Y   2
24426   Y   24
24430   Y   4
24430   Y   48
24442   Y   5
24442   Y   60
24453   Y   5
24453   Y   60
24460   Y   2
24460   Y   24
24523   Y   4
24523   Y   48
24530   Y   3
24530   Y   36
24546   Y   5
24546   Y   60
24554   Y   4
24554   Y   48
24558   Y   4
24558   Y   48
24559   Y   3
24559   Y   36
24592   Y   3
24592   Y   36
24696   Y   4
24696   Y   48
24697   Y   1
24697   Y   12
24758   Y   4
24758   Y   48
24759   Y   2
24759   Y   24
24800   Y   3
24800   Y   36
24814   Y   4
24814   Y   48
24860   Y   4
24860   Y   48
24871   Y   5
24871   Y   60
24872   Y   2
24872   Y   24
24895   Y   4
24895   Y   48
24896   Y   2
24896   Y   24
24905   Y   2
24905   Y   24
24918   Y   3
24918   Y   36
24921   Y   3
24921   Y   36
24924   Y   4
24924   Y   48
24927   Y   3
24927   Y   36
24943   Y   4
24943   Y   48
24952   Y   2
24952   Y   24
25018   Y   3
25018   Y   36
25049   Y   4
25049   Y   48
25053   Y   4
25053   Y   48
25069   Y   4
25069   Y   48
25074   Y   4
25074   Y   48
25098   Y   4
25098   Y   48
25101   Y   3
25101   Y   36
25114   Y   3
25114   Y   36
25128   Y   3
25128   Y   36
25139   Y   5
25139   Y   60
25153   Y   4
25153   Y   48
25168   Y   3
25168   Y   36
25169   Y   1
25169   Y   12
25179   Y   5
25179   Y   60
25184   Y   5
25184   Y   60
25185   Y   3
25185   Y   36
25195   Y   3
25195   Y   36
25201   Y   2
25201   Y   24
25223   Y   2
25223   Y   24
25227   Y   3
25227   Y   36
25289   Y   3
25289   Y   36
25303   Y   3
25303   Y   36
25312   Y   2
25312   Y   24
25320   Y   3
25320   Y   36
25323   Y   4
25323   Y   48
25324   Y   4
25324   Y   48
25325   Y   1
25325   Y   12
25347   Y   5
25347   Y   60
25348   Y   3
25348   Y   36
25349   Y   1
25349   Y   12
25377   Y   3
25377   Y   36
25395   Y   3
25395   Y   36
25403   Y   3
25403   Y   36
25466   Y   2
25466   Y   24
25478   Y   4
25478   Y   48
25479   Y   2
25479   Y   24
25498   Y   4
25498   Y   48
25531   Y   2
25531   Y   24
25538   Y   4
25538   Y   48
25590   Y   1
25590   Y   12
25594   Y   3
25594   Y   36
25619   Y   5
25619   Y   60
25620   Y   3
25620   Y   36
25707   Y   1
25707   Y   12
25782   Y   4
25782   Y   48
25797   Y   2
25797   Y   24
25801   Y   4
25801   Y   48
25826   Y   2
25826   Y   24
25869   Y   4
25869   Y   48
25878   Y   3
25878   Y   36
25914   Y   3
25914   Y   36
25955   Y   3
25955   Y   36
26008   Y   4
26008   Y   48
26011   Y   2
26011   Y   24
26013   Y   2
26013   Y   24
26018   Y   4
26018   Y   48
26039   Y   3
26039   Y   36
26049   Y   3
26049   Y   36
26094   Y   4
26094   Y   48
26095   Y   2
26095   Y   24
26106   Y   2
26106   Y   24
26113   Y   4
26113   Y   48
26126   Y   4
26126   Y   48
26138   Y   5
26138   Y   60
26142   Y   3
26142   Y   36
26155   Y   3
26155   Y   36
26227   Y   4
26227   Y   48
26318   Y   3
26318   Y   36
26374   Y   3
26374   Y   36
26394   Y   1
26394   Y   12
26399   Y   1
26399   Y   12
26415   Y   2
26415   Y   24
26448   Y   4
26448   Y   48
26465   Y   3
26465   Y   36
26488   Y   3
26488   Y   36
26553   Y   5
26553   Y   60
26554   Y   3
26554   Y   36
26564   Y   4
26564   Y   48
26565   Y   2
26565   Y   24
26568   Y   1
26568   Y   12
26582   Y   3
26582   Y   36
26604   Y   5
26604   Y   60
26606   Y   2
26606   Y   24
26609   Y   5
26609   Y   60
26610   Y   3
26610   Y   36
26626   Y   4
26626   Y   48
26628   Y   3
26628   Y   36
26648   Y   4
26648   Y   48
26665   Y   3
26665   Y   36
26706   Y   3
26706   Y   36
26714   Y   4
26714   Y   48
26715   Y   2
26715   Y   24
26731   Y   3
26731   Y   36
26756   Y   3
26756   Y   36
26765   Y   2
26765   Y   24
26778   Y   4
26778   Y   48
26789   Y   2
26789   Y   24
26820   Y   2
26820   Y   24
26884   Y   1
26884   Y   12
26910   Y   3
26910   Y   36
26926   Y   3
26926   Y   36
26980   Y   4
26980   Y   48
27048   Y   5
27048   Y   60
27051   Y   2
27051   Y   24
27061   Y   3
27061   Y   36
27075   Y   2
27075   Y   24
27094   Y   5
27094   Y   60
27126   Y   5
27126   Y   60
27138   Y   4
27138   Y   48
27155   Y   4
27155   Y   48
27180   Y   4
27180   Y   48
27191   Y   3
27191   Y   36
27192   Y   3
27192   Y   36
27195   Y   5
27195   Y   60
27196   Y   4
27196   Y   48
27241   Y   4
27241   Y   48
27245   Y   4
27245   Y   48
27285   Y   3
27285   Y   36
27308   Y   4
27308   Y   48
27309   Y   3
27309   Y   36
27327   Y   2
27327   Y   24
27350   Y   3
27350   Y   36
27366   Y   4
27366   Y   48
27379   Y   2
27379   Y   24
27388   Y   4
27388   Y   48
27394   Y   4
27394   Y   48
27409   Y   4
27409   Y   48
27469   Y   4
27469   Y   48
27498   Y   3
27498   Y   36
27534   Y   4
27534   Y   48
27535   Y   2
27535   Y   24
27562   Y   3
27562   Y   36
27620   Y   3
27620   Y   36
27631   Y   3
27631   Y   36
27659   Y   2
27659   Y   24
27719   Y   4
27719   Y   48
27734   Y   2
27734   Y   24
27738   Y   3
27738   Y   36
27788   Y   4
27788   Y   48
27793   Y   4
27793   Y   48
27824   Y   5
27824   Y   60
27837   Y   4
27837   Y   48
27853   Y   3
27853   Y   36
27906   Y   4
27906   Y   48
27943   Y   4
27943   Y   48
27961   Y   3
27961   Y   36
27969   Y   4
27969   Y   48
28017   Y   4
28017   Y   48
28062   Y   4
28062   Y   48
28121   Y   3
28121   Y   36
28151   Y   5
28151   Y   60
28168   Y   4
28168   Y   48
28180   Y   5
28180   Y   60
28193   Y   2
28193   Y   24
28215   Y   3
28215   Y   36
28235   Y   3
28235   Y   36
28287   Y   4
28287   Y   48
28297   Y   3
28297   Y   36
28307   Y   4
28307   Y   48
28314   Y   2
28314   Y   24
28334   Y   2
28334   Y   24
28443   Y   3
28443   Y   36
28453   Y   4
28453   Y   48
28454   Y   3
28454   Y   36
28479   Y   4
28479   Y   48
28486   Y   4
28486   Y   48
28489   Y   4
28489   Y   48
28527   Y   3
28527   Y   36
28535   Y   4
28535   Y   48
28539   Y   4
28539   Y   48
28544   Y   4
28544   Y   48
28548   Y   3
28548   Y   36
28566   Y   3
28566   Y   36
28597   Y   4
28597   Y   48
28598   Y   2
28598   Y   24
28610   Y   3
28610   Y   36
28611   Y   2
28611   Y   24
28663   Y   4
28663   Y   48
28675   Y   3
28675   Y   36
28701   Y   3
28701   Y   36
28712   Y   2
28712   Y   24
28727   Y   1
28727   Y   12
28794   Y   4
28794   Y   48
28822   Y   2
28822   Y   24
28835   Y   4
28835   Y   48
28852   Y   4
28852   Y   48
28881   Y   3
28881   Y   36
28904   Y   1
28904   Y   12
28974   Y   5
28974   Y   60
29008   Y   5
29008   Y   60
29009   Y   3
29009   Y   36
29043   Y   3
29043   Y   36
29049   Y   4
29049   Y   48
29070   Y   3
29070   Y   36
29128   Y   4
29128   Y   48
29132   Y   4
29132   Y   48
29196   Y   3
29196   Y   36
29238   Y   4
29238   Y   48
29239   Y   3
29239   Y   36
29265   Y   3
29265   Y   36
29294   Y   4
29294   Y   48
29304   Y   2
29304   Y   24
29343   Y   3
29343   Y   36
29348   Y   4
29348   Y   48
29352   Y   3
29352   Y   36
29396   Y   4
29396   Y   48
29414   Y   3
29414   Y   36
29422   Y   5
29422   Y   60
29423   Y   3
29423   Y   36
29426   Y   3
29426   Y   36
29444   Y   2
29444   Y   24
29469   Y   2
29469   Y   24
29499   Y   2
29499   Y   24
29521   Y   4
29521   Y   48
29527   Y   5
29527   Y   60
29528   Y   3
29528   Y   36
29619   Y   4
29619   Y   48
29626   Y   4
29626   Y   48
29629   Y   4
29629   Y   48
29654   Y   3
29654   Y   36
29706   Y   5
29706   Y   60
29709   Y   5
29709   Y   60
29736   Y   3
29736   Y   36
29757   Y   4
29757   Y   48
29976   Y   3
29976   Y   36
29981   Y   4
29981   Y   48
29982   Y   2
29982   Y   24
30025   Y   3
30025   Y   36
30028   Y   4
30028   Y   48
30055   Y   1
30055   Y   12
30063   Y   3
30063   Y   36
30100   Y   5
30100   Y   60
30120   Y   3
30120   Y   36
30123   Y   5
30123   Y   60
30167   Y   4
30167   Y   48
30173   Y   3
30173   Y   36
30217   Y   4
30217   Y   48
30219   Y   3
30219   Y   36
30240   Y   4
30240   Y   48
30245   Y   4
30245   Y   48
30268   Y   5
30268   Y   60
30277   Y   4
30277   Y   48
30297   Y   2
30297   Y   24
30306   Y   2
30306   Y   24
30333   Y   5
30333   Y   60
30334   Y   3
30334   Y   36
30346   Y   4
30346   Y   48
30372   Y   5
30372   Y   60
30373   Y   3
30373   Y   36
30395   Y   4
30395   Y   48
30404   Y   5
30404   Y   60
30407   Y   2
30407   Y   24
30502   Y   3
30502   Y   36
30517   Y   3
30517   Y   36
30520   Y   4
30520   Y   48
30534   Y   2
30534   Y   24
30535   Y   1
30535   Y   12
30583   Y   3
30583   Y   36
30589   Y   3
30589   Y   36
30669   Y   5
30669   Y   60
30670   Y   3
30670   Y   36
30704   Y   2
30704   Y   24
30720   Y   4
30720   Y   48
30725   Y   3
30725   Y   36
30741   Y   3
30741   Y   36
30770   Y   4
30770   Y   48
30771   Y   2
30771   Y   24
30783   Y   2
30783   Y   24
30789   Y   4
30789   Y   48
30831   Y   4
30831   Y   48
30832   Y   2
30832   Y   24
30836   Y   3
30836   Y   36
30896   Y   4
30896   Y   48
30900   Y   3
30900   Y   36
30903   Y   3
30903   Y   36
30906   Y   1
30906   Y   12
30960   Y   4
30960   Y   48
30976   Y   4
30976   Y   48
30977   Y   3
30977   Y   36
30982   Y   4
30982   Y   48
30984   Y   5
30984   Y   60
30985   Y   4
30985   Y   48
30989   Y   5
30989   Y   60
30998   Y   5
30998   Y   60
31043   Y   4
31043   Y   48
31048   Y   5
31048   Y   60
31052   Y   3
31052   Y   36
31070   Y   3
31070   Y   36
31084   Y   1
31084   Y   12
31093   Y   4
31093   Y   48
31111   Y   5
31111   Y   60
31133   Y   5
31133   Y   60
31228   Y   3
31228   Y   36
31237   Y   3
31237   Y   36
31244   Y   4
31244   Y   48
31256   Y   3
31256   Y   36
31262   Y   3
31262   Y   36
31284   Y   3
31284   Y   36
31298   Y   5
31298   Y   60
31301   Y   4
31301   Y   48
31323   Y   4
31323   Y   48
31370   Y   5
31370   Y   60
31371   Y   4
31371   Y   48
31403   Y   3
31403   Y   36
31435   Y   3
31435   Y   36
31441   Y   2
31441   Y   24
31447   Y

In [ ]:
for i in data[data['age_code'] == 'D'].index:
    x = data['age'][i]
    print(i,' ',data['age_code'][i],' ',data['age'][i])
    if data['age'][i] < 15:
        data['age'][i] = 0
    else :
        data['age'][i] = 1
    print(i,' ',data['age_code'][i],' ',data['age'][i])

In [ ]:
data.columns.values

In [ ]:
data = data.drop(['age_code', 'day_or_month_for_breast_feeding_','treatment_type'] , axis=1)

In [ ]:
data.columns.values

In [ ]:
data.shape

In [78]:
for i in data.columns:
    print(i)
    print(data[i][data[i] == -1].value_counts())

state_code
Series([], Name: state_code, dtype: int64)
record_code_iodine
Series([], Name: record_code_iodine, dtype: int64)
sex
Series([], Name: sex, dtype: int64)
age
Series([], Name: age, dtype: int64)
weight_in_kg
Series([], Name: weight_in_kg, dtype: int64)
length_height_cm
Series([], Name: length_height_cm, dtype: int64)
haemoglobin_level
Series([], Name: haemoglobin_level, dtype: int64)
first_breast_feeding
Series([], Name: first_breast_feeding, dtype: int64)
is_cur_breast_feeding
Series([], Name: is_cur_breast_feeding, dtype: int64)
day_or_month_for_breast_feeding
Series([], Name: day_or_month_for_breast_feeding, dtype: int64)
water_month
Series([], Name: water_month, dtype: int64)
ani_milk_month
Series([], Name: ani_milk_month, dtype: int64)
semisolid_month_or_day
Series([], Name: semisolid_month_or_day, dtype: int64)
solid_month
Series([], Name: solid_month, dtype: int64)
vegetables_month_or_day
Series([], Name: vegetables_month_or_day, dtype: int64)
illness_type
Series([], Name: illness_type, dtype: int64)
treatment_type
-1    11091
Name: treatment_type, dtype: int64

In [79]:
#data.to_csv('cleaned data/MP.csv', encoding='utf-8', index=False)